using DevComponents.DotNetBar;
using SkypeApps.Properties;
using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace SkypeApps
{
    partial class Form1
    {
        /// <summary>
        /// Variable nécessaire au concepteur.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Nettoyage des ressources utilisées.
        /// </summary>
        /// <param name="disposing">true si les ressources managées doivent être supprimées ; sinon, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code généré par le Concepteur Windows Form

        /// <summary>
        /// Méthode requise pour la prise en charge du concepteur - ne modifiez pas
        /// le contenu de cette méthode avec l'éditeur de code.
        /// </summary>
        private void InitializeComponent()
        {
//            components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager manager = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            skypeTheme1 = new SkypeTheme.SkypeTheme.SkypeTheme.SkypeTheme();
            linkLabel1 = new LinkLabel();
            label17 = new Label();
            label16 = new Label();
            skypeGroupbox3 = new SkypeTheme.SkypeTheme.SkypeTheme.SkypeGroupbox();
//            tabControl2 = new TabControl();
            tabControlPanel3 = new DevComponents.DotNetBar.TabControlPanel();
            label11 = new Label();
            skypeTextbox9 = new SkypeTheme.SkypeTheme.SkypeTheme.SkypeTextbox();
            label4 = new Label();
            skypeCallButton2 = new SkypeTheme.SkypeTheme.SkypeTheme.SkypeCallButton();
            skypeTextbox2 = new SkypeTheme.SkypeTheme.SkypeTheme.SkypeTextbox();
            label10 = new Label();
            skypeTextbox3 = new SkypeTheme.SkypeTheme.SkypeTheme.SkypeTextbox();
            label9 = new Label();
            skypeTextbox4 = new SkypeTheme.SkypeTheme.SkypeTheme.SkypeTextbox();
            label8 = new Label();
            skypeTextbox5 = new SkypeTheme.SkypeTheme.SkypeTheme.SkypeTextbox();
            label7 = new Label();
            skypeTextbox6 = new SkypeTheme.SkypeTheme.SkypeTheme.SkypeTextbox();
            label6 = new Label();
            skypeTextbox7 = new SkypeTheme.SkypeTheme.SkypeTheme.SkypeTextbox();
            label5 = new Label();
            skypeTextbox8 = new SkypeTheme.SkypeTheme.SkypeTheme.SkypeTextbox();
//            tabItem3 = new DevComponents.DotNetBar.TabItem(components);
            tabControlPanel4 = new DevComponents.DotNetBar.TabControlPanel();
            pictureBox5 = new PictureBox();
            pictureBox4 = new PictureBox();
            pictureBox3 = new PictureBox();
            pictureBox2 = new PictureBox();
            pictureBox1 = new PictureBox();
            radioButton5 = new RadioButton();
            radioButton4 = new RadioButton();
            radioButton3 = new RadioButton();
            radioButton2 = new RadioButton();
            skypeCallButton1 = new SkypeTheme.SkypeTheme.SkypeTheme.SkypeCallButton();
            radioButton1 = new RadioButton();
//            tabItem4 = new DevComponents.DotNetBar.TabItem(components);
            tabControlPanel6 = new DevComponents.DotNetBar.TabControlPanel();
            label12 = new Label();
            skypeButton4 = new SkypeTheme.SkypeTheme.SkypeTheme.SkypeButton();
            skypeButton3 = new SkypeTheme.SkypeTheme.SkypeTheme.SkypeButton();
            skypeButton2 = new SkypeTheme.SkypeTheme.SkypeTheme.SkypeButton();
            skypeButton1 = new SkypeTheme.SkypeTheme.SkypeTheme.SkypeButton();
            skypeCallButton4 = new SkypeTheme.SkypeTheme.SkypeTheme.SkypeCallButton();
            richTextBox2 = new RichTextBox();
            //tabItem6 = new DevComponents.DotNetBar.TabItem(components);
            LinkSkypeProcess = new SkypeTheme.SkypeTheme.SkypeTheme.SkypeButton();
            skypeGroupbox2 = new SkypeTheme.SkypeTheme.SkypeTheme.SkypeGroupbox();
            listView1 = new ListView();
            Contacts = new ColumnHeader();
            IDSkype = new ColumnHeader();
//            contextMenuStrip1 = new ContextMenuStrip(components);
            callToolStripMenuItem = new ToolStripMenuItem();
            startToolStripMenuItem = new ToolStripMenuItem();
            stopToolStripMenuItem = new ToolStripMenuItem();
            skypeGroupbox1 = new SkypeTheme.SkypeTheme.SkypeTheme.SkypeGroupbox();
           // tabControl1 = new TabControl();
            tabControlPanel1 = new DevComponents.DotNetBar.TabControlPanel();
            Secondes = new ComboBox();
            Minutes = new ComboBox();
            label18 = new Label();
            label23 = new Label();
            label24 = new Label();
            Hours = new ComboBox();
            label22 = new Label();
            label21 = new Label();
            label20 = new Label();
            Days = new ComboBox();
            Months = new ComboBox();
            Years = new ComboBox();
            label19 = new Label();
            skypeTextbox11 = new SkypeTheme.SkypeTheme.SkypeTheme.SkypeTextbox();
            richTextBox3 = new RichTextBox();
            skypeCallButton6 = new SkypeTheme.SkypeTheme.SkypeTheme.SkypeCallButton();
//            tabItem1 = new DevComponents.DotNetBar.TabItem(components);
            tabControlPanel5 = new DevComponents.DotNetBar.TabControlPanel();
            label15 = new Label();
            listBox1 = new ListBox();
            label13 = new Label();
            label14 = new Label();
            skypeTextbox10 = new SkypeTheme.SkypeTheme.SkypeTheme.SkypeTextbox();
            skypeCheckbox1 = new SkypeTheme.SkypeTheme.SkypeTheme.SkypeCheckbox();
            skypeCallButton5 = new SkypeTheme.SkypeTheme.SkypeTheme.SkypeCallButton();
           // tabItem5 = new DevComponents.DotNetBar.TabItem(components);
            tabControlPanel2 = new DevComponents.DotNetBar.TabControlPanel();
            SendMessage = new SkypeTheme.SkypeTheme.SkypeTheme.SkypeCallButton();
            label3 = new Label();
            Spam = new SkypeTheme.SkypeTheme.SkypeTheme.SkypeCheckbox();
            label2 = new Label();
            label1 = new Label();
            skypeTextbox1 = new SkypeTheme.SkypeTheme.SkypeTheme.SkypeTextbox();
            All = new SkypeTheme.SkypeTheme.SkypeTheme.SkypeCheckbox();
            richTextBox1 = new RichTextBox();
//            tabItem2 = new DevComponents.DotNetBar.TabItem(components);
            OpenSkype = new SkypeTheme.SkypeTheme.SkypeTheme.SkypeButton();
  //          SpamTimer = new Timer(components);
    //        notifyIcon1 = new NotifyIcon(components);
            linkLabel2 = new LinkLabel();
            label25 = new Label();
            skypeTheme1.SuspendLayout();
            skypeGroupbox3.SuspendLayout();
//            tabControl2.BeginInit();
//            tabControl2.SuspendLayout();
  //          tabControlPanel3.SuspendLayout();
    //        tabControlPanel4.SuspendLayout();
            ((ISupportInitialize)pictureBox5).BeginInit();
            ((ISupportInitialize)pictureBox4).BeginInit();
            ((ISupportInitialize)pictureBox3).BeginInit();
            ((ISupportInitialize)pictureBox2).BeginInit();
            ((ISupportInitialize)pictureBox1).BeginInit();
            tabControlPanel6.SuspendLayout();
            skypeGroupbox2.SuspendLayout();
            contextMenuStrip1.SuspendLayout();
            skypeGroupbox1.SuspendLayout();
            //tabControl1.BeginInit();
//            tabControl1.SuspendLayout();
  //          tabControlPanel1.SuspendLayout();
    //        tabControlPanel5.SuspendLayout();
      //      tabControlPanel2.SuspendLayout();
            base.SuspendLayout();
            skypeTheme1.BorderStyle = FormBorderStyle.FixedSingle;
            skypeTheme1.Controls.Add(label25);
            skypeTheme1.Controls.Add(linkLabel2);
            skypeTheme1.Controls.Add(linkLabel1);
            skypeTheme1.Controls.Add(label17);
            skypeTheme1.Controls.Add(label16);
            skypeTheme1.Controls.Add(skypeGroupbox3);
            skypeTheme1.Controls.Add(LinkSkypeProcess);
            skypeTheme1.Controls.Add(skypeGroupbox2);
            skypeTheme1.Controls.Add(skypeGroupbox1);
            skypeTheme1.Controls.Add(OpenSkype);
            skypeTheme1.Dock = DockStyle.Fill;
            skypeTheme1.Font = new System.Drawing.Font("Verdana", 8f);
            skypeTheme1.Image = null;
            skypeTheme1.ImeMode = ImeMode.NoControl;
            skypeTheme1.Location = new System.Drawing.Point(0, 0);
            skypeTheme1.Movable = false;
            skypeTheme1.Name = "skypeTheme1";
            skypeTheme1.NoRounding = false;
            skypeTheme1.Sizable = false;
            skypeTheme1.Size = new System.Drawing.Size(730, 460);
            skypeTheme1.SmartBounds = true;
            skypeTheme1.StartPosition = FormStartPosition.WindowsDefaultLocation;
            skypeTheme1.TabIndex = 0;
            skypeTheme1.TransparencyKey = System.Drawing.Color.Fuchsia;
            skypeTheme1.Transparent = false;
            skypeTheme1.Click += new EventHandler(skypeTheme1_Click);
            linkLabel1.ActiveLinkColor = SystemColors.Highlight;
            linkLabel1.AutoSize = true;
            linkLabel1.BackColor = Color.Transparent;
            linkLabel1.LinkColor = SystemColors.HotTrack;
            linkLabel1.Location = new Point(470, 0x1b9);
            linkLabel1.Name = "linkLabel1";
            linkLabel1.Size = new Size(0x88, 13);
            linkLabel1.TabIndex = 6;
            linkLabel1.TabStop = true;
            linkLabel1.Text = "UnknownDevTeam.org";
            linkLabel1.LinkClicked += new LinkLabelLinkClickedEventHandler(linkLabel1_LinkClicked);
            label17.AutoSize = true;
            label17.BackColor = Color.Transparent;
            label17.ForeColor = Color.Black;
            label17.Location = new Point(0x1ad, 0x1b9);
            label17.Name = "label17";
            label17.Size = new Size(0x2c, 13);
            label17.TabIndex = 5;
            label17.Text = "Visit : ";
            label16.AutoSize = true;
            label16.BackColor = Color.Transparent;
            label16.ForeColor = Color.Black;
            label16.Location = new Point(6, 0x1b9);
            label16.Name = "label16";
            label16.Size = new Size(0x86, 13);
            label16.TabIndex = 4;
            label16.Text = "Created by Unknauwn";
            skypeGroupbox3.BackColor = Color.White;
            skypeGroupbox3.BottomBar = true;
            skypeGroupbox3.Caption = true;
//            skypeGroupbox3.CaptionImage(Resources.Profil);
 //           skypeGroupbox3.CaptionText("About User");
            skypeGroupbox3.Controls.Add(tabControl2);
            skypeGroupbox3.Enabled = false;
            skypeGroupbox3.ForeColor = Color.Maroon;
            skypeGroupbox3.Location = new Point(0x1e8, 0x31);
            skypeGroupbox3.Name = "skypeGroupbox3";
            skypeGroupbox3.Size = new Size(0xe9, 0x185);
            skypeGroupbox3.TabIndex = 3;
            skypeGroupbox3.Text = "User Infomations";
            tabControl2.BackColor = Color.Transparent;
            tabControl2.ColorScheme().TabBackground(Color.Transparent);
            tabControl2.ColorScheme().TabItemBackground(Color.Transparent);
            tabControl2.ColorScheme().TabItemBackground2(Color.Transparent);
            tabControl2.ColorScheme().TabItemBackgroundColorBlend().AddRange(new BackgroundColorBlend[] { new BackgroundColorBlend(Color.FromArgb(0xd7, 230, 0xf9), 0f), new BackgroundColorBlend(Color.FromArgb(0xc7, 220, 0xf8), 0.45f), new BackgroundColorBlend(Color.FromArgb(0xb3, 0xd0, 0xf5), 0.45f), new BackgroundColorBlend(Color.FromArgb(0xd7, 0xe5, 0xf7), 1f) });
            tabControl2.ColorScheme().TabItemBorder(Color.Transparent);
            tabControl2.ColorScheme().TabItemBorderDark(Color.Transparent);
            tabControl2.ColorScheme().TabItemHotBackgroundColorBlend().AddRange(new BackgroundColorBlend[] { new BackgroundColorBlend(Color.FromArgb(0xff, 0xfd, 0xeb), 0f), new BackgroundColorBlend(Color.FromArgb(0xff, 0xec, 0xa8), 0.45f), new BackgroundColorBlend(Color.FromArgb(0xff, 0xda, 0x59), 0.45f), new BackgroundColorBlend(Color.FromArgb(0xff, 230, 0x8d), 1f) });
            tabControl2.ColorScheme().TabItemSelectedBackgroundColorBlend().AddRange(new BackgroundColorBlend[] { new BackgroundColorBlend(Color.White, 0f), new BackgroundColorBlend(Color.FromArgb(0xfd, 0xfd, 0xfe), 0.45f), new BackgroundColorBlend(Color.FromArgb(0xfd, 0xfd, 0xfe), 0.45f), new BackgroundColorBlend(Color.FromArgb(0xfd, 0xfd, 0xfe), 1f) });
            tabControl2.ColorScheme().TabItemSelectedBorder(Color.Transparent);
            tabControl2.ColorScheme().TabItemSelectedText(SystemColors.Highlight);
            tabControl2.ColorScheme().TabItemSeparator(Color.Transparent);
            tabControl2.ColorScheme().TabPanelBackground2(Color.White);
            tabControl2.ColorScheme().TabPanelBorder(Color.Transparent);
            tabControl2.Controls.Add(tabControlPanel4);
            tabControl2.Controls.Add(tabControlPanel3);
            tabControl2.Controls.Add(tabControlPanel6);
            tabControl2.Location = new Point(2, 0x21);
            tabControl2.Name = "tabControl2";
            tabControl2.SelectedTabFont(new Font("Verdana", 8f, FontStyle.Bold));
            tabControl2.SelectedTabIndex(0);
            tabControl2.ShowFocusRectangle = false;
            tabControl2.Size = new Size(0xe3, 0x149);
            tabControl2.Style(7);
            tabControl2.TabIndex = 1;
            tabControl2.TabLayoutType(1);
            tabControl2.Tabs().Add(tabItem4);
            tabControl2.Tabs().Add(tabItem3);
            tabControl2.Tabs().Add(tabItem6);
            tabControl2.Text = "tabControl2";
            tabControlPanel3.Controls.Add(label11);
            tabControlPanel3.Controls.Add(skypeTextbox9);
            tabControlPanel3.Controls.Add(label4);
            tabControlPanel3.Controls.Add(skypeCallButton2);
            tabControlPanel3.Controls.Add(skypeTextbox2);
            tabControlPanel3.Controls.Add(label10);
            tabControlPanel3.Controls.Add(skypeTextbox3);
            tabControlPanel3.Controls.Add(label9);
            tabControlPanel3.Controls.Add(skypeTextbox4);
            tabControlPanel3.Controls.Add(label8);
            tabControlPanel3.Controls.Add(skypeTextbox5);
            tabControlPanel3.Controls.Add(label7);
            tabControlPanel3.Controls.Add(skypeTextbox6);
            tabControlPanel3.Controls.Add(label6);
            tabControlPanel3.Controls.Add(skypeTextbox7);
            tabControlPanel3.Controls.Add(label5);
            tabControlPanel3.Controls.Add(skypeTextbox8);
            tabControlPanel3.Dock = DockStyle.Fill;
            tabControlPanel3.Location = new Point(0, 0x1a);
            tabControlPanel3.Name = "tabControlPanel3";
            tabControlPanel3.Padding = new Padding(1);
            tabControlPanel3.Size = new Size(0xe3, 0x12f);
            tabControlPanel3.Style.BackColor2.Color = (Color.White);
            tabControlPanel3.Style.BackgroundImage = (Resources.Separator3);
            tabControlPanel3.Style.BackgroundImagePosition = (3);
            tabControlPanel3.Style.Border = (1);
            tabControlPanel3.Style.BorderColor.Color = (Color.Transparent);
            tabControlPanel3.Style.BorderSide = (11);
            tabControlPanel3.Style.GradientAngle = (90);
            tabControlPanel3.TabIndex = 2;
            tabControlPanel3.TabItem = (tabItem3);
            label11.AutoSize = true;
            label11.BackColor = Color.Transparent;
            label11.ForeColor = SystemColors.Highlight;
            label11.Location = new Point(1, 0x63);
            label11.Name = "label11";
            label11.Size = new Size(0x47, 13);
            label11.TabIndex = 0x13;
            label11.Text = "About me :";
            skypeTextbox9.Colors = (new Bloom[0]);
            skypeTextbox9.Customization = ("");
            skypeTextbox9.Font = (new Font("Verdana", 8f));
            skypeTextbox9.Image = (null);
            skypeTextbox9.Location = new Point(0x53, 0xf2);
            skypeTextbox9.MaxLength = (0x7fff);
            skypeTextbox9.Multiline = false;
            skypeTextbox9.Name = "skypeTextbox9";
            skypeTextbox9.NoRounding = false;
            skypeTextbox9.ReadOnly = false;
            skypeTextbox9.Size = new Size(0x87, 0x18);
            skypeTextbox9.TabIndex = 0x12;
            skypeTextbox9.TextAlign(HorizontalAlignment.Left);
            skypeTextbox9.Transparent = false;
            skypeTextbox9.UseSystemPasswordChar = false;
            label4.AutoSize = true;
            label4.BackColor = Color.Transparent;
            label4.ForeColor = SystemColors.Highlight;
            label4.Location = new Point(1, 0x26);
            label4.Name = "label4";
            label4.Size = new Size(0x31, 13);
            label4.TabIndex = 9;
            label4.Text = "Name :";
            skypeCallButton2.Colors(new Bloom[0]);
            skypeCallButton2.Customization("");
            skypeCallButton2.Font(new Font("Arial", 10f, FontStyle.Bold));
            skypeCallButton2.Image((Image)manager.GetObject("skypeCallButton2.Image"));
            skypeCallButton2.Location = new Point(0x17, 0x112);
            skypeCallButton2.Name = "skypeCallButton2";
            skypeCallButton2.NoRounding = false;
            skypeCallButton2.Size = new Size(0xab, 0x19);
            skypeCallButton2.TabIndex = 0x11;
            skypeCallButton2.Text("Set Profil Infos");
            skypeCallButton2.Transparent = false;
            skypeCallButton2.Click += new EventHandler(skypeCallButton2_Click);
            skypeTextbox2.Colors(new Bloom[0]);
            skypeTextbox2.Customization("");
            skypeTextbox2.Font(new Font("Verdana", 8f));
            skypeTextbox2.Image(null);
            skypeTextbox2.Location = new Point(0x53, 0x20);
            skypeTextbox2.MaxLength(0x7fff);
            skypeTextbox2.Multiline = false;
            skypeTextbox2.Name = "skypeTextbox2";
            skypeTextbox2.NoRounding = false;
            skypeTextbox2.ReadOnly = false;
            skypeTextbox2.Size = new Size(0x87, 0x18);
            skypeTextbox2.TabIndex = 0;
            skypeTextbox2.TextAlign(HorizontalAlignment.Left);
            skypeTextbox2.Transparent = false;
            skypeTextbox2.UseSystemPasswordChar = false;
            label10.AutoSize = true;
            label10.BackColor = Color.Transparent;
            label10.ForeColor = SystemColors.Highlight;
            label10.Location = new Point(1, 0xf8);
            label10.Name = "label10";
            label10.Size = new Size(0x4d, 13);
            label10.TabIndex = 15;
            label10.Text = "HomePage :";
            skypeTextbox3.Colors(new Bloom[0]);
            skypeTextbox3.Customization("");
            skypeTextbox3.Font(new Font("Verdana", 8f));
            skypeTextbox3.Image(null);
            skypeTextbox3.Location = new Point(0x53, 0x3e);
            skypeTextbox3.MaxLength(0x7fff);
            skypeTextbox3.Multiline = false;
            skypeTextbox3.Name = "skypeTextbox3";
            skypeTextbox3.NoRounding = false;
            skypeTextbox3.ReadOnly = false;
            skypeTextbox3.Size = new Size(0x87, 0x18);
            skypeTextbox3.TabIndex = 1;
            skypeTextbox3.TextAlign(HorizontalAlignment.Left);
            skypeTextbox3.Transparent = false;
            skypeTextbox3.UseSystemPasswordChar = false;
            label9.AutoSize = true;
            label9.BackColor = Color.Transparent;
            label9.ForeColor = SystemColors.Highlight;
            label9.Location = new Point(1, 0xdb);
            label9.Name = "label9";
            label9.Size = new Size(0x27, 13);
            label9.TabIndex = 14;
            label9.Text = "City :";
            skypeTextbox4.Colors(new Bloom[0]);
            skypeTextbox4.Customization("");
            skypeTextbox4.Font(new Font("Verdana", 8f));
            skypeTextbox4.Image(null);
            skypeTextbox4.Location = new Point(0x53, 0x5c);
            skypeTextbox4.MaxLength(0x7fff);
            skypeTextbox4.Multiline = false;
            skypeTextbox4.Name = "skypeTextbox4";
            skypeTextbox4.NoRounding = false;
            skypeTextbox4.ReadOnly = false;
            skypeTextbox4.Size = new Size(0x87, 0x18);
            skypeTextbox4.TabIndex = 2;
            skypeTextbox4.TextAlign(HorizontalAlignment.Left);
            skypeTextbox4.Transparent = false;
            skypeTextbox4.UseSystemPasswordChar = false;
            label8.AutoSize = true;
            label8.BackColor = Color.Transparent;
            label8.ForeColor = SystemColors.Highlight;
            label8.Location = new Point(1, 190);
            label8.Name = "label8";
            label8.Size = new Size(0x3e, 13);
            label8.TabIndex = 13;
            label8.Text = "Country :";
            skypeTextbox5.Colors(new Bloom[0]);
            skypeTextbox5.Customization("");
            skypeTextbox5.Font(new Font("Verdana", 8f));
            skypeTextbox5.Image(null);
            skypeTextbox5.Location = new Point(0x53, 0x7a);
            skypeTextbox5.MaxLength(0x7fff);
            skypeTextbox5.Multiline = false;
            skypeTextbox5.Name = "skypeTextbox5";
            skypeTextbox5.NoRounding = false;
            skypeTextbox5.ReadOnly = false;
            skypeTextbox5.Size = new Size(0x87, 0x18);
            skypeTextbox5.TabIndex = 3;
            skypeTextbox5.TextAlign(HorizontalAlignment.Left);
            skypeTextbox5.Transparent = false;
            skypeTextbox5.UseSystemPasswordChar = false;
            label7.AutoSize = true;
            label7.BackColor = Color.Transparent;
            label7.ForeColor = SystemColors.Highlight;
            label7.Location = new Point(1, 0x9f);
            label7.Name = "label7";
            label7.Size = new Size(0x3e, 13);
            label7.TabIndex = 12;
            label7.Text = "Phone 2 :";
            skypeTextbox6.Colors(new Bloom[0]);
            skypeTextbox6.Customization("");
            skypeTextbox6.Font(new Font("Verdana", 8f));
            skypeTextbox6.Image(null);
            skypeTextbox6.Location = new Point(0x53, 0x98);
            skypeTextbox6.MaxLength(0x7fff);
            skypeTextbox6.Multiline = false;
            skypeTextbox6.Name = "skypeTextbox6";
            skypeTextbox6.NoRounding = false;
            skypeTextbox6.ReadOnly = false;
            skypeTextbox6.Size = new Size(0x87, 0x18);
            skypeTextbox6.TabIndex = 4;
            skypeTextbox6.TextAlign(HorizontalAlignment.Left);
            skypeTextbox6.Transparent = false;
            skypeTextbox6.UseSystemPasswordChar = false;
            label6.AutoSize = true;
            label6.BackColor = Color.Transparent;
            label6.ForeColor = SystemColors.Highlight;
            label6.Location = new Point(1, 130);
            label6.Name = "label6";
            label6.Size = new Size(0x33, 13);
            label6.TabIndex = 11;
            label6.Text = "Phone :";
            skypeTextbox7.Colors(new Bloom[0]);
            skypeTextbox7.Customization("");
            skypeTextbox7.Font(new Font("Verdana", 8f));
            skypeTextbox7.Image(null);
            skypeTextbox7.Location = new Point(0x53, 0xb6);
            skypeTextbox7.MaxLength(0x7fff);
            skypeTextbox7.Multiline = false;
            skypeTextbox7.Name = "skypeTextbox7";
            skypeTextbox7.NoRounding = false;
            skypeTextbox7.ReadOnly = false;
            skypeTextbox7.Size = new Size(0x87, 0x18);
            skypeTextbox7.TabIndex = 5;
            skypeTextbox7.TextAlign(HorizontalAlignment.Left);
            skypeTextbox7.Transparent = false;
            skypeTextbox7.UseSystemPasswordChar = false;
            label5.AutoSize = true;
            label5.BackColor = Color.Transparent;
            label5.ForeColor = SystemColors.Highlight;
            label5.Location = new Point(1, 0x44);
            label5.Name = "label5";
            label5.Size = new Size(0x2e, 13);
            label5.TabIndex = 10;
            label5.Text = "Mood :";
            skypeTextbox8.Colors(new Bloom[0]);
            skypeTextbox8.Customization("");
            skypeTextbox8.Font(new Font("Verdana", 8f));
            skypeTextbox8.Image(null);
            skypeTextbox8.Location = new Point(0x53, 0xd4);
            skypeTextbox8.MaxLength(0x7fff);
            skypeTextbox8.Multiline = false;
            skypeTextbox8.Name = "skypeTextbox8";
            skypeTextbox8.NoRounding = false;
            skypeTextbox8.ReadOnly = false;
            skypeTextbox8.Size = new Size(0x87, 0x18);
            skypeTextbox8.TabIndex = 6;
            skypeTextbox8.TextAlign(HorizontalAlignment.Left);
            skypeTextbox8.Transparent = false;
            skypeTextbox8.UseSystemPasswordChar = false;
            tabItem3.AttachedControl(tabControlPanel3);
            tabItem3.Name("tabItem3");
            tabItem3.Text("Profil");
            tabControlPanel4.BackgroundImageLayout = ImageLayout.None;
            tabControlPanel4.Controls.Add(pictureBox5);
            tabControlPanel4.Controls.Add(pictureBox4);
            tabControlPanel4.Controls.Add(pictureBox3);
            tabControlPanel4.Controls.Add(pictureBox2);
            tabControlPanel4.Controls.Add(pictureBox1);
            tabControlPanel4.Controls.Add(radioButton5);
            tabControlPanel4.Controls.Add(radioButton4);
            tabControlPanel4.Controls.Add(radioButton3);
            tabControlPanel4.Controls.Add(radioButton2);
            tabControlPanel4.Controls.Add(skypeCallButton1);
            tabControlPanel4.Controls.Add(radioButton1);
            tabControlPanel4.Dock = DockStyle.Fill;
            tabControlPanel4.Location = new Point(0, 0x1a);
            tabControlPanel4.Name = "tabControlPanel4";
            tabControlPanel4.Padding = new Padding(1);
            tabControlPanel4.Size = new Size(0xe3, 0x12f);
            tabControlPanel4.Style.BackColor2().Color(Color.White);
            tabControlPanel4.Style.BackgroundImage((Image)manager.GetObject("tabControlPanel4.Style.BackgroundImage"));
            tabControlPanel4.Style.BackgroundImageAlpha(150);
            tabControlPanel4.Style.BackgroundImagePosition(3);
            tabControlPanel4.Style.Border(1);
            tabControlPanel4.Style.BorderColor().Color(Color.Transparent);
            tabControlPanel4.Style.BorderSide(11);
            tabControlPanel4.Style.GradientAngle(90);
            tabControlPanel4.TabIndex = 1;
            tabControlPanel4.TabItem(tabItem4);
            pictureBox5.BackColor = Color.Transparent;
            pictureBox5.Image = Resources.Invisible;
            pictureBox5.Location = new Point(0x17, 0xb2);
            pictureBox5.Name = "pictureBox5";
            pictureBox5.Size = new Size(0x19, 0x19);
            pictureBox5.SizeMode = PictureBoxSizeMode.StretchImage;
            pictureBox5.TabIndex = 0x11;
            pictureBox5.TabStop = false;
            pictureBox4.BackColor = Color.Transparent;
            pictureBox4.Image = Resources.Invisible;
            pictureBox4.Location = new Point(0x17, 0x93);
            pictureBox4.Name = "pictureBox4";
            pictureBox4.Size = new Size(0x19, 0x19);
            pictureBox4.SizeMode = PictureBoxSizeMode.StretchImage;
            pictureBox4.TabIndex = 0x10;
            pictureBox4.TabStop = false;
            pictureBox3.BackColor = Color.Transparent;
            pictureBox3.Image = Resources.Busy;
            pictureBox3.Location = new Point(0x17, 0x74);
            pictureBox3.Name = "pictureBox3";
            pictureBox3.Size = new Size(0x19, 0x19);
            pictureBox3.TabIndex = 15;
            pictureBox3.TabStop = false;
            pictureBox2.BackColor = Color.Transparent;
            pictureBox2.Image = Resources.Away;
            pictureBox2.Location = new Point(0x17, 0x55);
            pictureBox2.Name = "pictureBox2";
            pictureBox2.Size = new Size(0x19, 0x19);
            pictureBox2.SizeMode = PictureBoxSizeMode.StretchImage;
            pictureBox2.TabIndex = 14;
            pictureBox2.TabStop = false;
            pictureBox1.BackColor = Color.Transparent;
            pictureBox1.Image = Resources.Online;
            pictureBox1.Location = new Point(0x17, 0x36);
            pictureBox1.Name = "pictureBox1";
            pictureBox1.Size = new Size(0x19, 0x19);
            pictureBox1.SizeMode = PictureBoxSizeMode.StretchImage;
            pictureBox1.TabIndex = 13;
            pictureBox1.TabStop = false;
            radioButton5.AutoSize = true;
            radioButton5.BackColor = Color.Transparent;
            radioButton5.ForeColor = SystemColors.MenuHighlight;
            radioButton5.Location = new Point(0x4a, 0xb6);
            radioButton5.Name = "radioButton5";
            radioButton5.Size = new Size(0x65, 0x11);
            radioButton5.TabIndex = 12;
            radioButton5.TabStop = true;
            radioButton5.Text = "Disconnected";
            radioButton5.UseVisualStyleBackColor = false;
            radioButton4.AutoSize = true;
            radioButton4.BackColor = Color.Transparent;
            radioButton4.ForeColor = SystemColors.MenuHighlight;
            radioButton4.Location = new Point(0x4a, 0x97);
            radioButton4.Name = "radioButton4";
            radioButton4.Size = new Size(0x49, 0x11);
            radioButton4.TabIndex = 11;
            radioButton4.TabStop = true;
            radioButton4.Text = "Invisible";
            radioButton4.UseVisualStyleBackColor = false;
            radioButton3.AutoSize = true;
            radioButton3.BackColor = Color.Transparent;
            radioButton3.ForeColor = SystemColors.MenuHighlight;
            radioButton3.Location = new Point(0x4a, 120);
            radioButton3.Name = "radioButton3";
            radioButton3.Size = new Size(0x6d, 0x11);
            radioButton3.TabIndex = 10;
            radioButton3.TabStop = true;
            radioButton3.Text = "Do Not Disturb";
            radioButton3.UseVisualStyleBackColor = false;
            radioButton2.AutoSize = true;
            radioButton2.BackColor = Color.Transparent;
            radioButton2.ForeColor = SystemColors.MenuHighlight;
            radioButton2.Location = new Point(0x4a, 0x59);
            radioButton2.Name = "radioButton2";
            radioButton2.Size = new Size(0x38, 0x11);
            radioButton2.TabIndex = 9;
            radioButton2.TabStop = true;
            radioButton2.Text = "Away";
            radioButton2.UseVisualStyleBackColor = false;
            skypeCallButton1.Colors(new Bloom[0]);
            skypeCallButton1.Customization("");
            skypeCallButton1.Font(new Font("Arial", 10f, FontStyle.Bold));
            skypeCallButton1.Image((Image)manager.GetObject("skypeCallButton1.Image"));
            skypeCallButton1.Location = new Point(0x22, 0xf6);
            skypeCallButton1.Name = "skypeCallButton1";
            skypeCallButton1.NoRounding = false;
            skypeCallButton1.Size = new Size(0x94, 0x19);
            skypeCallButton1.TabIndex = 8;
            skypeCallButton1.Text("Update Status");
            skypeCallButton1.Transparent = false;
            skypeCallButton1.Visible = false;
            skypeCallButton1.Click += new EventHandler(skypeCallButton1_Click);
            radioButton1.AutoSize = true;
            radioButton1.BackColor = Color.Transparent;
            radioButton1.Checked = true;
            radioButton1.ForeColor = SystemColors.MenuHighlight;
            radioButton1.Location = new Point(0x4a, 0x39);
            radioButton1.Name = "radioButton1";
            radioButton1.Size = new Size(0x3d, 0x11);
            radioButton1.TabIndex = 0;
            radioButton1.TabStop = true;
            radioButton1.Text = "Online";
            radioButton1.UseVisualStyleBackColor = false;
            tabItem4.AttachedControl(tabControlPanel4);
            tabItem4.Name("tabItem4");
            tabItem4.Text("Status");
            tabControlPanel6.Controls.Add(label12);
            tabControlPanel6.Controls.Add(skypeButton4);
            tabControlPanel6.Controls.Add(skypeButton3);
            tabControlPanel6.Controls.Add(skypeButton2);
            tabControlPanel6.Controls.Add(skypeButton1);
            tabControlPanel6.Controls.Add(skypeCallButton4);
            tabControlPanel6.Controls.Add(richTextBox2);
            tabControlPanel6.Dock = DockStyle.Fill;
            tabControlPanel6.Location = new Point(0, 0x1a);
            tabControlPanel6.Name = "tabControlPanel6";
            tabControlPanel6.Padding = new Padding(1);
            tabControlPanel6.Size = new Size(0xe3, 0x12f);
            tabControlPanel6.Style.BackColor2().Color(Color.White);
            tabControlPanel6.Style.BackgroundImage((Image)manager.GetObject("tabControlPanel6.Style.BackgroundImage"));
            tabControlPanel6.Style.BackgroundImagePosition(3);
            tabControlPanel6.Style.Border(1);
            tabControlPanel6.Style.BorderColor().Color(Color.Transparent);
            tabControlPanel6.Style.BorderSide(11);
            tabControlPanel6.Style.GradientAngle(90);
            tabControlPanel6.TabIndex = 3;
            tabControlPanel6.TabItem(tabItem6);
            label12.AutoSize = true;
            label12.BackColor = Color.Transparent;
            label12.ForeColor = SystemColors.Highlight;
            label12.Location = new Point(6, 0x74);
            label12.Name = "label12";
            label12.Size = new Size(0xd9, 13);
            label12.TabIndex = 13;
            label12.Text = "Script .VBS Needed, => Google.com";
            skypeButton4.Colors(new Bloom[0]);
            skypeButton4.Customization("");
            skypeButton4.Font(new Font("Verdana", 8f));
            skypeButton4.Image((Image)manager.GetObject("skypeButton4.Image"));
            skypeButton4.ImageAllignmentMode(1);
            skypeButton4.Location = new Point(0x72, 0x42);
            skypeButton4.Name = "skypeButton4";
            skypeButton4.NoRounding = false;
            skypeButton4.Size = new Size(0x5f, 0x20);
            skypeButton4.TabIndex = 12;
            skypeButton4.Text("Underline");
            skypeButton4.Text_Margin_Left(0x19);
            skypeButton4.Transparent = false;
            skypeButton4.Click += new EventHandler(skypeButton4_Click);
            skypeButton3.Colors(new Bloom[0]);
            skypeButton3.Customization("");
            skypeButton3.Font(new Font("Verdana", 8f));
            skypeButton3.Image((Image)manager.GetObject("skypeButton3.Image"));
            skypeButton3.ImageAllignmentMode(1);
            skypeButton3.Location = new Point(13, 0x42);
            skypeButton3.Name = "skypeButton3";
            skypeButton3.NoRounding = false;
            skypeButton3.Size = new Size(0x5f, 0x20);
            skypeButton3.TabIndex = 11;
            skypeButton3.Text("Bold");
            skypeButton3.Text_Margin_Left(0x19);
            skypeButton3.Transparent = false;
            skypeButton3.Click += new EventHandler(skypeButton3_Click);
            skypeButton2.Colors(new Bloom[0]);
            skypeButton2.Customization("");
            skypeButton2.Font(new Font("Verdana", 8f));
            skypeButton2.Image((Image)manager.GetObject("skypeButton2.Image"));
            skypeButton2.ImageAllignmentMode(1);
            skypeButton2.Location = new Point(0x72, 0x1c);
            skypeButton2.Name = "skypeButton2";
            skypeButton2.NoRounding = false;
            skypeButton2.Size = new Size(0x5f, 0x20);
            skypeButton2.TabIndex = 10;
            skypeButton2.Text("Center");
            skypeButton2.Text_Margin_Left(0x19);
            skypeButton2.Transparent = false;
            skypeButton2.Click += new EventHandler(skypeButton2_Click);
            skypeButton1.Colors(new Bloom[0]);
            skypeButton1.Customization("");
            skypeButton1.Font(new Font("Verdana", 8f));
            skypeButton1.Image(Resources.BBCODE);
            skypeButton1.ImageAllignmentMode(1);
            skypeButton1.Location = new Point(13, 0x1c);
            skypeButton1.Name = "skypeButton1";
            skypeButton1.NoRounding = false;
            skypeButton1.Size = new Size(0x5f, 0x20);
            skypeButton1.TabIndex = 9;
            skypeButton1.Text("Blink");
            skypeButton1.Text_Margin_Left(0x19);
            skypeButton1.Transparent = false;
            skypeButton1.Click += new EventHandler(skypeButton1_Click);
            skypeCallButton4.Colors(new Bloom[0]);
            skypeCallButton4.Customization("");
            skypeCallButton4.Font(new Font("Arial", 10f, FontStyle.Bold));
            skypeCallButton4.Image((Image)manager.GetObject("skypeCallButton4.Image"));
            skypeCallButton4.Location = new Point(0x24, 0x84);
            skypeCallButton4.Name = "skypeCallButton4";
            skypeCallButton4.NoRounding = false;
            skypeCallButton4.Size = new Size(0x94, 0x19);
            skypeCallButton4.TabIndex = 8;
            skypeCallButton4.Text("Set Custom Mood");
            skypeCallButton4.Transparent = false;
            skypeCallButton4.Click += new EventHandler(skypeCallButton4_Click);
            richTextBox2.BackColor = SystemColors.InactiveBorder;
            richTextBox2.BorderStyle = BorderStyle.None;
            richTextBox2.DetectUrls = false;
            richTextBox2.Location = new Point(0, 0xac);
            richTextBox2.Name = "richTextBox2";
            richTextBox2.Size = new Size(0xe3, 0x85);
            richTextBox2.TabIndex = 1;
            richTextBox2.Text = "Enter Mood here...";
            tabItem6.AttachedControl(tabControlPanel6);
            tabItem6.Name("tabItem6");
            tabItem6.Text("Mood Advanced");
            LinkSkypeProcess.Colors(new Bloom[0]);
            LinkSkypeProcess.Customization("");
            LinkSkypeProcess.Font(new Font("Verdana", 8f));
            LinkSkypeProcess.Image(Resources.Link);
            LinkSkypeProcess.ImageAllignmentMode(1);
            LinkSkypeProcess.Location = new Point(0x1e8, 11);
            LinkSkypeProcess.Name = "LinkSkypeProcess";
            LinkSkypeProcess.NoRounding = false;
            LinkSkypeProcess.Size = new Size(0xe9, 0x20);
            LinkSkypeProcess.TabIndex = 2;
            LinkSkypeProcess.Text("Link Skype Process");
            LinkSkypeProcess.Text_Margin_Left(0x19);
            LinkSkypeProcess.Transparent = false;
            LinkSkypeProcess.Click += new EventHandler(LinkSkypeProcess_Click);
            skypeGroupbox2.BackColor = Color.White;
            skypeGroupbox2.BottomBar = true;
            skypeGroupbox2.Caption = true;
            skypeGroupbox2.CaptionImage((Image)manager.GetObject("skypeGroupbox2.CaptionImage"));
            skypeGroupbox2.CaptionText("Contacts List");
            skypeGroupbox2.Controls.Add(listView1);
            skypeGroupbox2.Location = new Point(3, 12);
            skypeGroupbox2.Name = "skypeGroupbox2";
            skypeGroupbox2.Size = new Size(240, 0x1aa);
            skypeGroupbox2.TabIndex = 2;
            skypeGroupbox2.Text = "Contacts";
            listView1.BackColor = SystemColors.InactiveBorder;
            listView1.Columns.AddRange(new ColumnHeader[] { Contacts, IDSkype });
            listView1.ContextMenuStrip = contextMenuStrip1;
            listView1.FullRowSelect = true;
            listView1.Location = new Point(6, 0x25);
            listView1.Name = "listView1";
            listView1.Size = new Size(0xe4, 0x16c);
            listView1.TabIndex = 3;
            listView1.UseCompatibleStateImageBehavior = false;
            listView1.View = View.Details;
            listView1.SelectedIndexChanged += new EventHandler(listView1_SelectedIndexChanged);
            Contacts.Text = "Contacts";
            Contacts.Width = 0x97;
            IDSkype.Text = "IDSkype";
            IDSkype.Width = 0x47;
            contextMenuStrip1.Items.AddRange(new ToolStripItem[] { callToolStripMenuItem });
            contextMenuStrip1.Name = "contextMenuStrip1";
            contextMenuStrip1.Size = new Size(0x5f, 0x1a);
            callToolStripMenuItem.DropDownItems.AddRange(new ToolStripItem[] { startToolStripMenuItem, stopToolStripMenuItem });
            callToolStripMenuItem.Image = Resources.Call;
            callToolStripMenuItem.Name = "callToolStripMenuItem";
            callToolStripMenuItem.Size = new Size(0x5e, 0x16);
            callToolStripMenuItem.Text = "Call";
            startToolStripMenuItem.Image = Resources.StartCall;
            startToolStripMenuItem.Name = "startToolStripMenuItem";
            startToolStripMenuItem.Size = new Size(0x62, 0x16);
            startToolStripMenuItem.Text = "Start";
            startToolStripMenuItem.Click += new EventHandler(startToolStripMenuItem_Click);
            stopToolStripMenuItem.Image = Resources.StopCall;
            stopToolStripMenuItem.Name = "stopToolStripMenuItem";
            stopToolStripMenuItem.Size = new Size(0x62, 0x16);
            stopToolStripMenuItem.Text = "Stop";
            stopToolStripMenuItem.Click += new EventHandler(stopToolStripMenuItem_Click);
            skypeGroupbox1.BackColor = Color.White;
            skypeGroupbox1.BottomBar = true;
            skypeGroupbox1.Caption = true;
            skypeGroupbox1.CaptionImage(Resources.Message);
            skypeGroupbox1.CaptionText("Messages Panel");
            skypeGroupbox1.Controls.Add(tabControl1);
            skypeGroupbox1.Enabled = false;
            skypeGroupbox1.ForeColor = Color.Maroon;
            skypeGroupbox1.Location = new Point(0xf9, 0x31);
            skypeGroupbox1.Name = "skypeGroupbox1";
            skypeGroupbox1.Size = new Size(0xe9, 0x185);
            skypeGroupbox1.TabIndex = 1;
            skypeGroupbox1.Text = "About Messages";
            tabControl1.BackColor = Color.Transparent;
            tabControl1.CanReorderTabs = true;
            tabControl1.ColorScheme().TabBackground(Color.Transparent);
            tabControl1.ColorScheme().TabItemBackground(Color.Transparent);
            tabControl1.ColorScheme().TabItemBackground2(Color.Transparent);
            tabControl1.ColorScheme().TabItemBackgroundColorBlend().AddRange(new BackgroundColorBlend[] { new BackgroundColorBlend(Color.FromArgb(0xd7, 230, 0xf9), 0f), new BackgroundColorBlend(Color.FromArgb(0xc7, 220, 0xf8), 0.45f), new BackgroundColorBlend(Color.FromArgb(0xb3, 0xd0, 0xf5), 0.45f), new BackgroundColorBlend(Color.FromArgb(0xd7, 0xe5, 0xf7), 1f) });
            tabControl1.ColorScheme().TabItemBorder(Color.Transparent);
            tabControl1.ColorScheme().TabItemBorderDark(Color.Transparent);
            tabControl1.ColorScheme().TabItemHotBackgroundColorBlend().AddRange(new BackgroundColorBlend[] { new BackgroundColorBlend(Color.FromArgb(0xff, 0xfd, 0xeb), 0f), new BackgroundColorBlend(Color.FromArgb(0xff, 0xec, 0xa8), 0.45f), new BackgroundColorBlend(Color.FromArgb(0xff, 0xda, 0x59), 0.45f), new BackgroundColorBlend(Color.FromArgb(0xff, 230, 0x8d), 1f) });
            tabControl1.ColorScheme().TabItemSelectedBackgroundColorBlend().AddRange(new BackgroundColorBlend[] { new BackgroundColorBlend(Color.White, 0f), new BackgroundColorBlend(Color.FromArgb(0xfd, 0xfd, 0xfe), 0.45f), new BackgroundColorBlend(Color.FromArgb(0xfd, 0xfd, 0xfe), 0.45f), new BackgroundColorBlend(Color.FromArgb(0xfd, 0xfd, 0xfe), 1f) });
            tabControl1.ColorScheme().TabItemSelectedBorder(Color.Transparent);
            tabControl1.ColorScheme().TabItemSelectedText(SystemColors.Highlight);
            tabControl1.ColorScheme().TabItemSeparator(Color.Transparent);
            tabControl1.ColorScheme().TabPanelBackground2(Color.White);
            tabControl1.ColorScheme().TabPanelBorder(Color.Transparent);
            tabControl1.Controls.Add(tabControlPanel2);
            tabControl1.Controls.Add(tabControlPanel1);
            tabControl1.Controls.Add(tabControlPanel5);
            tabControl1.Location = new Point(3, 0x24);
            tabControl1.Name = "tabControl1";
            tabControl1.SelectedTabFont(new Font("Verdana", 8f, FontStyle.Bold));
            tabControl1.SelectedTabIndex(1);
            tabControl1.ShowFocusRectangle = false;
            tabControl1.Size = new Size(0xe3, 0x148);
            tabControl1.Style(7);
            tabControl1.TabIndex = 2;
            tabControl1.TabLayoutType(1);
            tabControl1.Tabs().Add(tabItem2);
            tabControl1.Tabs().Add(tabItem5);
            tabControl1.Tabs().Add(tabItem1);
            tabControl1.Text = "tabControl2";
            tabControlPanel1.Controls.Add(Secondes);
            tabControlPanel1.Controls.Add(Minutes);
            tabControlPanel1.Controls.Add(label18);
            tabControlPanel1.Controls.Add(label23);
            tabControlPanel1.Controls.Add(label24);
            tabControlPanel1.Controls.Add(Hours);
            tabControlPanel1.Controls.Add(label22);
            tabControlPanel1.Controls.Add(label21);
            tabControlPanel1.Controls.Add(label20);
            tabControlPanel1.Controls.Add(Days);
            tabControlPanel1.Controls.Add(Months);
            tabControlPanel1.Controls.Add(Years);
            tabControlPanel1.Controls.Add(label19);
            tabControlPanel1.Controls.Add(skypeTextbox11);
            tabControlPanel1.Controls.Add(richTextBox3);
            tabControlPanel1.Controls.Add(skypeCallButton6);
            tabControlPanel1.Dock = DockStyle.Fill;
            tabControlPanel1.Location = new Point(0, 0x1a);
            tabControlPanel1.Name = "tabControlPanel1";
            tabControlPanel1.Padding = new Padding(1);
            tabControlPanel1.Size = new Size(0xe3, 0x12e);
            tabControlPanel1.Style.BackColor2().Color(Color.White);
            tabControlPanel1.Style.BackgroundImage(Resources.Separator4);
            tabControlPanel1.Style.BackgroundImagePosition(3);
            tabControlPanel1.Style.Border(1);
            tabControlPanel1.Style.BorderColor().Color(Color.Transparent);
            tabControlPanel1.Style.BorderSide(11);
            tabControlPanel1.Style.GradientAngle(90);
            tabControlPanel1.TabIndex = 6;
            tabControlPanel1.TabItem(tabItem1);
            Secondes.FormattingEnabled = true;
            Secondes.Items.AddRange(new object[] {
                "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16",
                "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32",
                "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48",
                "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59"
             });
            Secondes.Location = new Point(0x92, 0x8f);
            Secondes.Name = "Secondes";
            Secondes.Size = new Size(0x2a, 0x15);
            Secondes.TabIndex = 0x1d;
            Minutes.FormattingEnabled = true;
            Minutes.Items.AddRange(new object[] {
                "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16",
                "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32",
                "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48",
                "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59"
             });
            Minutes.Location = new Point(0x58, 0x8f);
            Minutes.Name = "Minutes";
            Minutes.Size = new Size(0x2a, 0x15);
            Minutes.TabIndex = 0x1c;
            label18.AutoSize = true;
            label18.BackColor = Color.Transparent;
            label18.ForeColor = SystemColors.Highlight;
            label18.Location = new Point(0x8f, 0x7f);
            label18.Name = "label18";
            label18.Size = new Size(0x40, 13);
            label18.TabIndex = 0x1b;
            label18.Text = "Seconds :";
            label23.AutoSize = true;
            label23.BackColor = Color.Transparent;
            label23.ForeColor = SystemColors.Highlight;
            label23.Location = new Point(0x55, 0x7f);
            label23.Name = "label23";
            label23.Size = new Size(0x3b, 13);
            label23.TabIndex = 0x1a;
            label23.Text = "Minutes :";
            label24.AutoSize = true;
            label24.BackColor = Color.Transparent;
            label24.ForeColor = SystemColors.Highlight;
            label24.Location = new Point(0x1a, 0x7f);
            label24.Name = "label24";
            label24.Size = new Size(0x31, 13);
            label24.TabIndex = 0x19;
            label24.Text = "Hours :";
            Hours.FormattingEnabled = true;
            Hours.Items.AddRange(new object[] {
                "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15",
                "16", "17", "18", "19", "20", "21", "22", "23"
             });
            Hours.Location = new Point(0x1d, 0x8f);
            Hours.Name = "Hours";
            Hours.Size = new Size(0x2a, 0x15);
            Hours.TabIndex = 0x16;
            label22.AutoSize = true;
            label22.BackColor = Color.Transparent;
            label22.ForeColor = SystemColors.Highlight;
            label22.Location = new Point(0x94, 80);
            label22.Name = "label22";
            label22.Size = new Size(0x2d, 13);
            label22.TabIndex = 0x15;
            label22.Text = "Days :";
            label21.AutoSize = true;
            label21.BackColor = Color.Transparent;
            label21.ForeColor = SystemColors.Highlight;
            label21.Location = new Point(0x5b, 80);
            label21.Name = "label21";
            label21.Size = new Size(0x38, 13);
            label21.TabIndex = 20;
            label21.Text = "Months :";
            label20.AutoSize = true;
            label20.BackColor = Color.Transparent;
            label20.ForeColor = SystemColors.Highlight;
            label20.Location = new Point(0x15, 80);
            label20.Name = "label20";
            label20.Size = new Size(0x2f, 13);
            label20.TabIndex = 0x13;
            label20.Text = "Years :";
            Days.FormattingEnabled = true;
            Days.Items.AddRange(new object[] {
                "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16",
                "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31"
             });
            Days.Location = new Point(0x97, 0x60);
            Days.Name = "Days";
            Days.Size = new Size(0x33, 0x15);
            Days.TabIndex = 0x12;
            Months.FormattingEnabled = true;
            Months.Items.AddRange(new object[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" });
            Months.Location = new Point(0x5e, 0x60);
            Months.Name = "Months";
            Months.Size = new Size(0x33, 0x15);
            Months.TabIndex = 0x11;
            Years.FormattingEnabled = true;
            Years.Items.AddRange(new object[] {
                "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010",
                "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020"
             });
            Years.Location = new Point(0x18, 0x60);
            Years.Name = "Years";
            Years.Size = new Size(0x40, 0x15);
            Years.TabIndex = 0x10;
            label19.AutoSize = true;
            label19.BackColor = Color.Transparent;
            label19.ForeColor = SystemColors.Highlight;
            label19.Location = new Point(0x58, 0x1a);
            label19.Name = "label19";
            label19.Size = new Size(0x2d, 13);
            label19.TabIndex = 13;
            label19.Text = "From :";
            skypeTextbox11.Colors(new Bloom[0]);
            skypeTextbox11.Customization("");
            skypeTextbox11.Font(new Font("Verdana", 8f));
            skypeTextbox11.Image(null);
            skypeTextbox11.Location = new Point(12, 0x2a);
            skypeTextbox11.MaxLength(0x7fff);
            skypeTextbox11.Multiline = false;
            skypeTextbox11.Name = "skypeTextbox11";
            skypeTextbox11.NoRounding = false;
            skypeTextbox11.ReadOnly = false;
            skypeTextbox11.Size = new Size(200, 0x18);
            skypeTextbox11.TabIndex = 12;
            skypeTextbox11.TextAlign(HorizontalAlignment.Left);
            skypeTextbox11.Transparent = false;
            skypeTextbox11.UseSystemPasswordChar = false;
            richTextBox3.BackColor = SystemColors.InactiveBorder;
            richTextBox3.BorderStyle = BorderStyle.None;
            richTextBox3.DetectUrls = false;
            richTextBox3.Location = new Point(0, 0xe3);
            richTextBox3.Name = "richTextBox3";
            richTextBox3.Size = new Size(0xe3, 0x4b);
            richTextBox3.TabIndex = 11;
            richTextBox3.Text = "Enter Message here...";
            skypeCallButton6.Colors(new Bloom[0]);
            skypeCallButton6.Customization("");
            skypeCallButton6.Font(new Font("Arial", 10f, FontStyle.Bold));
            skypeCallButton6.Image(Resources.Send);
            skypeCallButton6.Location = new Point(0x18, 0xc4);
            skypeCallButton6.Name = "skypeCallButton6";
            skypeCallButton6.NoRounding = false;
            skypeCallButton6.Size = new Size(0xb2, 0x19);
            skypeCallButton6.TabIndex = 10;
            skypeCallButton6.Text("Copy Fake Quote");
            skypeCallButton6.Transparent = false;
            skypeCallButton6.Click += new EventHandler(skypeCallButton6_Click);
            tabItem1.AttachedControl(tabControlPanel1);
            tabItem1.Name("tabItem1");
            tabItem1.Text("Fake Quote");
            tabControlPanel5.Controls.Add(label15);
            tabControlPanel5.Controls.Add(listBox1);
            tabControlPanel5.Controls.Add(label13);
            tabControlPanel5.Controls.Add(label14);
            tabControlPanel5.Controls.Add(skypeTextbox10);
            tabControlPanel5.Controls.Add(skypeCheckbox1);
            tabControlPanel5.Controls.Add(skypeCallButton5);
            tabControlPanel5.Cursor = Cursors.Default;
            tabControlPanel5.Dock = DockStyle.Fill;
            tabControlPanel5.Location = new Point(0, 0x1a);
            tabControlPanel5.Name = "tabControlPanel5";
            tabControlPanel5.Padding = new Padding(1);
            tabControlPanel5.Size = new Size(0xe3, 0x12e);
            tabControlPanel5.Style.BackColor2().Color(Color.White);
            tabControlPanel5.Style.BackgroundImage((Image)manager.GetObject("tabControlPanel5.Style.BackgroundImage"));
            tabControlPanel5.Style.BackgroundImagePosition(3);
            tabControlPanel5.Style.Border(1);
            tabControlPanel5.Style.BorderColor().Color(Color.Transparent);
            tabControlPanel5.Style.BorderSide(11);
            tabControlPanel5.Style.GradientAngle(90);
            tabControlPanel5.TabIndex = 5;
            tabControlPanel5.TabItem(tabItem5);
            label15.AutoSize = true;
            label15.BackColor = Color.Transparent;
            label15.ForeColor = SystemColors.Highlight;
            label15.Location = new Point(40, 0x60);
            label15.Name = "label15";
            label15.Size = new Size(0x8e, 13);
            label15.TabIndex = 15;
            label15.Text = "List of SmileyMessage :";
            listBox1.FormattingEnabled = true;
            listBox1.Items.AddRange(new object[] {
                "BUG", "BearHug", "Fuck", "Dick", "Boobs", "Boobs2", "Boobs3", "KissYou", "Apple", "TeddyBear", "Rabbit", "I Love Sex", "Super Mario", "Butterfly", "Alright", "LOL",
                "OK(love)", "Drink", "Love", "Jerk Off"
             });
            listBox1.Location = new Point(0x1d, 0x72);
            listBox1.Name = "listBox1";
            listBox1.Size = new Size(0xa3, 0x86);
            listBox1.TabIndex = 14;
            label13.AutoSize = true;
            label13.BackColor = Color.Transparent;
            label13.ForeColor = SystemColors.Highlight;
            label13.Location = new Point(0x62, 0x44);
            label13.Name = "label13";
            label13.Size = new Size(0x1f, 13);
            label13.TabIndex = 13;
            label13.Text = "All ?";
            label14.AutoSize = true;
            label14.BackColor = Color.Transparent;
            label14.ForeColor = SystemColors.Highlight;
            label14.Location = new Point(0x4e, 0x19);
            label14.Name = "label14";
            label14.Size = new Size(60, 13);
            label14.TabIndex = 12;
            label14.Text = "Contact :";
            skypeTextbox10.Colors(new Bloom[0]);
            skypeTextbox10.Customization("");
            skypeTextbox10.Font(new Font("Verdana", 8f));
            skypeTextbox10.Image(null);
            skypeTextbox10.Location = new Point(12, 0x29);
            skypeTextbox10.MaxLength(0x7fff);
            skypeTextbox10.Multiline = false;
            skypeTextbox10.Name = "skypeTextbox10";
            skypeTextbox10.NoRounding = false;
            skypeTextbox10.ReadOnly = false;
            skypeTextbox10.Size = new Size(200, 0x18);
            skypeTextbox10.TabIndex = 11;
            skypeTextbox10.TextAlign(HorizontalAlignment.Left);
            skypeTextbox10.Transparent = false;
            skypeTextbox10.UseSystemPasswordChar = false;
            skypeCheckbox1.BackColor(SystemColors.Highlight);
            skypeCheckbox1.Checked = false;
            skypeCheckbox1.Colors(new Bloom[0]);
            skypeCheckbox1.Customization("");
            skypeCheckbox1.Font(new Font("Verdana", 8f));
            skypeCheckbox1.Image(null);
            skypeCheckbox1.Location = new Point(0x4e, 0x43);
            skypeCheckbox1.Name = "skypeCheckbox1";
            skypeCheckbox1.NoRounding = false;
            skypeCheckbox1.Size = new Size(14, 14);
            skypeCheckbox1.TabIndex = 10;
            skypeCheckbox1.Text("All?");
            skypeCheckbox1.Transparent = false;
            skypeCheckbox1.add_CheckedChanged(new SkypeTheme.SkypeTheme.SkypeTheme.SkypeCheckbox.CheckedChangedEventHandler(this, (IntPtr)skypeCheckbox1_CheckedChanged));
            skypeCallButton5.Colors(new Bloom[0]);
            skypeCallButton5.Customization("");
            skypeCallButton5.Font(new Font("Arial", 10f, FontStyle.Bold));
            skypeCallButton5.Image(Resources.Send);
            skypeCallButton5.Location = new Point(0x18, 0x109);
            skypeCallButton5.Name = "skypeCallButton5";
            skypeCallButton5.NoRounding = false;
            skypeCallButton5.Size = new Size(0xb2, 0x19);
            skypeCallButton5.TabIndex = 9;
            skypeCallButton5.Text("Send Custom Message");
            skypeCallButton5.Transparent = false;
            skypeCallButton5.Click += new EventHandler(skypeCallButton5_Click);
            tabItem5.AttachedControl(tabControlPanel5);
            tabItem5.Name("tabItem5");
            tabItem5.Text("Custom Message");
            tabControlPanel2.Controls.Add(SendMessage);
            tabControlPanel2.Controls.Add(label3);
            tabControlPanel2.Controls.Add(Spam);
            tabControlPanel2.Controls.Add(label2);
            tabControlPanel2.Controls.Add(label1);
            tabControlPanel2.Controls.Add(skypeTextbox1);
            tabControlPanel2.Controls.Add(All);
            tabControlPanel2.Controls.Add(richTextBox1);
            tabControlPanel2.Dock = DockStyle.Fill;
            tabControlPanel2.Location = new Point(0, 0x1a);
            tabControlPanel2.Name = "tabControlPanel2";
            tabControlPanel2.Padding = new Padding(1);
            tabControlPanel2.Size = new Size(0xe3, 0x12e);
            tabControlPanel2.Style.BackColor2().Color(Color.White);
            tabControlPanel2.Style.BackgroundImage((Image)manager.GetObject("tabControlPanel2.Style.BackgroundImage"));
            tabControlPanel2.Style.BackgroundImagePosition(3);
            tabControlPanel2.Style.Border(1);
            tabControlPanel2.Style.BorderColor().Color(Color.Transparent);
            tabControlPanel2.Style.BorderSide(11);
            tabControlPanel2.Style.GradientAngle(90);
            tabControlPanel2.TabIndex = 4;
            tabControlPanel2.TabItem(tabItem2);
            SendMessage.Colors(new Bloom[0]);
            SendMessage.Customization("");
            SendMessage.Font(new Font("Arial", 10f, FontStyle.Bold));
            SendMessage.Image(Resources.Send);
            SendMessage.Location = new Point(0x21, 0x81);
            SendMessage.Name = "SendMessage";
            SendMessage.NoRounding = false;
            SendMessage.Size = new Size(0x94, 0x19);
            SendMessage.TabIndex = 7;
            SendMessage.Text("Send Message");
            SendMessage.Transparent = false;
            SendMessage.Visible = false;
            SendMessage.Click += new EventHandler(SendMessage_Click);
            label3.AutoSize = true;
            label3.BackColor = Color.Transparent;
            label3.ForeColor = SystemColors.Highlight;
            label3.Location = new Point(0x83, 0x52);
            label3.Name = "label3";
            label3.Size = new Size(50, 13);
            label3.TabIndex = 6;
            label3.Text = "Spam ?";
            Spam.BackColor(SystemColors.Highlight);
            Spam.Checked = false;
            Spam.Colors(new Bloom[0]);
            Spam.Customization("");
            Spam.Font(new Font("Verdana", 8f));
            Spam.Image(null);
            Spam.Location = new Point(0x70, 0x51);
            Spam.Name = "Spam";
            Spam.NoRounding = false;
            Spam.Size = new Size(14, 14);
            Spam.TabIndex = 5;
            Spam.Text("All?");
            Spam.Transparent = false;
            Spam.add_CheckedChanged(new SkypeTheme.SkypeTheme.SkypeTheme.SkypeCheckbox.CheckedChangedEventHandler(this, Spam_CheckedChanged));
            label2.AutoSize = true;
            label2.BackColor = Color.Transparent;
            label2.ForeColor = SystemColors.Highlight;
            label2.Location = new Point(70, 0x52);
            label2.Name = "label2";
            label2.Size = new Size(0x1f, 13);
            label2.TabIndex = 4;
            label2.Text = "All ?";
            label1.AutoSize = true;
            label1.BackColor = Color.Transparent;
            label1.ForeColor = SystemColors.Highlight;
            label1.Location = new Point(0x4e, 0x23);
            label1.Name = "label1";
            label1.Size = new Size(60, 13);
            label1.TabIndex = 3;
            label1.Text = "Contact :";
            skypeTextbox1.Colors(new Bloom[0]);
            skypeTextbox1.Customization("");
            skypeTextbox1.Font(new Font("Verdana", 8f));
            skypeTextbox1.Image(null);
            skypeTextbox1.Location = new Point(12, 0x33);
            skypeTextbox1.MaxLength(0x7fff);
            skypeTextbox1.Multiline = false;
            skypeTextbox1.Name = "skypeTextbox1";
            skypeTextbox1.NoRounding = false;
            skypeTextbox1.ReadOnly = false;
            skypeTextbox1.Size = new Size(200, 0x18);
            skypeTextbox1.TabIndex = 2;
            skypeTextbox1.TextAlign(HorizontalAlignment.Left);
            skypeTextbox1.Transparent = false;
            skypeTextbox1.UseSystemPasswordChar = false;
            All.BackColor(SystemColors.Highlight);
            All.Checked = false;
            All.Colors(new Bloom[0]);
            All.Customization("");
            All.Font(new Font("Verdana", 8f));
            All.Image(null);
            All.Location = new Point(50, 0x51);
            All.Name = "All";
            All.NoRounding = false;
            All.Size = new Size(14, 14);
            All.TabIndex = 1;
            All.Text("All?");
            All.Transparent = false;
            All.add_CheckedChanged(new SkypeTheme.SkypeTheme.SkypeTheme.SkypeCheckbox.CheckedChangedEventHandler(All_CheckedChanged));
            richTextBox1.BackColor = SystemColors.InactiveBorder;
            richTextBox1.BorderStyle = BorderStyle.None;
            richTextBox1.DetectUrls = false;
            richTextBox1.Location = new Point(0, 0xa9);
            richTextBox1.Name = "richTextBox1";
            richTextBox1.Size = new Size(0xe3, 0x85);
            richTextBox1.TabIndex = 0;
            richTextBox1.Text = "Enter Message here...";
            tabItem2.AttachedControl(tabControlPanel2);
            tabItem2.Name("tabItem2");
            tabItem2.Text("Messages");
            OpenSkype.Colors(new Bloom[0]);
            OpenSkype.Customization("");
            OpenSkype.Font(new Font("Verdana", 8f));
            OpenSkype.Image(Resources.Open);
            OpenSkype.ImageAllignmentMode(1);
            OpenSkype.Location = new Point(0xf9, 11);
            OpenSkype.Name = "OpenSkype";
            OpenSkype.NoRounding = false;
            OpenSkype.Size = new Size(0xe9, 0x20);
            OpenSkype.TabIndex = 0;
            OpenSkype.Text("Open Skype ?");
            OpenSkype.Text_Margin_Left(0x19);
            OpenSkype.Transparent = false;
            OpenSkype.Click += new EventHandler(OpenSkype_Click);
            SpamTimer.Interval = 250;
            SpamTimer.Tick += new EventHandler(SpamTimer_Tick);
            notifyIcon1.BalloonTipIcon = ToolTipIcon.Info;
            notifyIcon1.BalloonTipText = "Skype Apps Manager has been reduced,\r\nYou can launch it again from here : )";
            notifyIcon1.Icon = (Icon)manager.GetObject("notifyIcon1.Icon");
            notifyIcon1.Text = "Hey! : )";
            notifyIcon1.Visible = true;
            notifyIcon1.MouseDoubleClick += new MouseEventHandler(notifyIcon1_MouseDoubleClick);
            linkLabel2.ActiveLinkColor = SystemColors.Highlight;
            linkLabel2.AutoSize = true;
            linkLabel2.BackColor = Color.Transparent;
            linkLabel2.LinkColor = SystemColors.HotTrack;
            linkLabel2.Location = new Point(0x265, 0x1b9);
            linkLabel2.Name = "linkLabel2";
            linkLabel2.Size = new Size(0x6c, 13);
            linkLabel2.TabIndex = 7;
            linkLabel2.TabStop = true;
            linkLabel2.Text = "HackAndModz.net";
            linkLabel2.LinkClicked += new LinkLabelLinkClickedEventHandler(linkLabel2_LinkClicked);
            label25.AutoSize = true;
            label25.BackColor = Color.Transparent;
            label25.ForeColor = Color.Black;
            label25.Location = new Point(0x25c, 0x1b9);
            label25.Name = "label25";
            label25.Size = new Size(12, 13);
            label25.TabIndex = 8;
            label25.Text = "|";
            base.AutoScaleDimensions = new SizeF(6f, 13f);
            base.AutoScaleMode = AutoScaleMode.Font;
            base.ClientSize = new Size(730, 460);
            base.Controls.Add(skypeTheme1);
            base.FormBorderStyle = FormBorderStyle.FixedSingle;
            base.Icon = (Icon)manager.GetObject("$Icon");
            base.MaximizeBox = false;
            base.Name = "Form1";
            base.Opacity = 0.98;
            Text = "Skype Apps Manager";
            base.TransparencyKey = Color.Fuchsia;
            base.Resize += new EventHandler(Form1_Resize);
            skypeTheme1.ResumeLayout = false;
            skypeTheme1.PerformLayout();
            skypeGroupbox3.ResumeLayout = false;
            tabControl2.EndInit();
            tabControl2.ResumeLayout = false;
            tabControlPanel3.ResumeLayout = false;
            tabControlPanel3.PerformLayout();
            tabControlPanel4.ResumeLayout = false;
            tabControlPanel4.PerformLayout();
            ((ISupportInitialize)pictureBox5).EndInit();
            ((ISupportInitialize)pictureBox4).EndInit();
            ((ISupportInitialize)pictureBox3).EndInit();
            ((ISupportInitialize)pictureBox2).EndInit();
            ((ISupportInitialize)pictureBox1).EndInit();
            tabControlPanel6.ResumeLayout = false;
            tabControlPanel6.PerformLayout();
            skypeGroupbox2.ResumeLayout = false;
            contextMenuStrip1.ResumeLayout = false;
            skypeGroupbox1.ResumeLayout = false;
            tabControl1.EndInit();
            tabControl1.ResumeLayout = false;
            tabControlPanel1.ResumeLayout = false;
            tabControlPanel1.PerformLayout();
            tabControlPanel5.ResumeLayout = false;
            tabControlPanel5.PerformLayout();
            tabControlPanel2.ResumeLayout = false;
            tabControlPanel2.PerformLayout();
            base.ResumeLayout = false;
        }
        #endregion


        private SkypeTheme.SkypeTheme.SkypeTheme.SkypeCheckbox All;
        private ToolStripMenuItem callToolStripMenuItem;
        private System.ComponentModel.IContainer components;
        private ColumnHeader Contacts;
        private ContextMenuStrip contextMenuStrip1;
        private ComboBox Days;
       
        private ComboBox Hours;
        private ColumnHeader IDSkype;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.Label label15;
        private System.Windows.Forms.Label label16;
        private System.Windows.Forms.Label label17;
        private System.Windows.Forms.Label label18;
        private System.Windows.Forms.Label label19;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label20;
        private System.Windows.Forms.Label label21;
        private System.Windows.Forms.Label label22;
        private System.Windows.Forms.Label label23;
        private System.Windows.Forms.Label label24;
        private System.Windows.Forms.Label label25;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.LinkLabel linkLabel1;
        private System.Windows.Forms.LinkLabel linkLabel2;
        private SkypeTheme.SkypeTheme.SkypeTheme.SkypeButton LinkSkypeProcess;
        private ListBox listBox1;
        private ListView listView1;
        private System.Windows.Forms.ComboBox Minutes;
        private System.Windows.Forms.ComboBox Months;
        private System.Windows.Forms.NotifyIcon notifyIcon1;
        private SkypeTheme.SkypeTheme.SkypeTheme.SkypeButton OpenSkype;
        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.PictureBox pictureBox2;
        private System.Windows.Forms.PictureBox pictureBox3;
        private System.Windows.Forms.PictureBox pictureBox4;
        private System.Windows.Forms.PictureBox pictureBox5;
        private System.Windows.Forms.RadioButton radioButton1;
        private System.Windows.Forms.RadioButton radioButton2;
        private System.Windows.Forms.RadioButton radioButton3;
        private System.Windows.Forms.RadioButton radioButton4;
        private System.Windows.Forms.RadioButton radioButton5;
        private System.Windows.Forms.RichTextBox richTextBox1;
        private System.Windows.Forms.RichTextBox richTextBox2;
        private System.Windows.Forms.RichTextBox richTextBox3;
        private System.Windows.Forms.ComboBox Secondes;
        private SkypeTheme.SkypeTheme.SkypeTheme.SkypeCallButton SendMessage;
       
        private SkypeTheme.SkypeTheme.SkypeTheme.SkypeButton skypeButton1;
        private SkypeTheme.SkypeTheme.SkypeTheme.SkypeButton skypeButton2;
        private SkypeTheme.SkypeTheme.SkypeTheme.SkypeButton skypeButton3;
        private SkypeTheme.SkypeTheme.SkypeTheme.SkypeButton skypeButton4;
        private SkypeTheme.SkypeTheme.SkypeTheme.SkypeCallButton skypeCallButton1;
        private SkypeTheme.SkypeTheme.SkypeTheme.SkypeCallButton skypeCallButton2;
        private SkypeTheme.SkypeTheme.SkypeTheme.SkypeCallButton skypeCallButton4;
        private SkypeTheme.SkypeTheme.SkypeTheme.SkypeCallButton skypeCallButton5;
        private SkypeTheme.SkypeTheme.SkypeTheme.SkypeCallButton skypeCallButton6;
        private SkypeTheme.SkypeTheme.SkypeTheme.SkypeCheckbox skypeCheckbox1;
        private SkypeTheme.SkypeTheme.SkypeTheme.SkypeGroupbox skypeGroupbox1;
        private SkypeTheme.SkypeTheme.SkypeTheme.SkypeGroupbox skypeGroupbox2;
        private SkypeTheme.SkypeTheme.SkypeTheme.SkypeGroupbox skypeGroupbox3;
        private SkypeTheme.SkypeTheme.SkypeTheme.SkypeTextbox skypeTextbox1;
        private SkypeTheme.SkypeTheme.SkypeTheme.SkypeTextbox skypeTextbox10;
        private SkypeTheme.SkypeTheme.SkypeTheme.SkypeTextbox skypeTextbox11;
        private SkypeTheme.SkypeTheme.SkypeTheme.SkypeTextbox skypeTextbox2;
        private SkypeTheme.SkypeTheme.SkypeTheme.SkypeTextbox skypeTextbox3;
        private SkypeTheme.SkypeTheme.SkypeTheme.SkypeTextbox skypeTextbox4;
        private SkypeTheme.SkypeTheme.SkypeTheme.SkypeTextbox skypeTextbox5;
        private SkypeTheme.SkypeTheme.SkypeTheme.SkypeTextbox skypeTextbox6;
        private SkypeTheme.SkypeTheme.SkypeTheme.SkypeTextbox skypeTextbox7;
        private SkypeTheme.SkypeTheme.SkypeTheme.SkypeTextbox skypeTextbox8;
        private SkypeTheme.SkypeTheme.SkypeTheme.SkypeTextbox skypeTextbox9;
        private SkypeTheme.SkypeTheme.SkypeTheme.SkypeTheme skypeTheme1;
        private SkypeTheme.SkypeTheme.SkypeTheme.SkypeCheckbox Spam;
        private Timer SpamTimer;
        private ToolStripMenuItem startToolStripMenuItem;
        private ToolStripMenuItem stopToolStripMenuItem;
        private TabControl tabControl1;
        private TabControl tabControl2;
        private DevComponents.DotNetBar.TabControlPanel tabControlPanel1;
        private DevComponents.DotNetBar.TabControlPanel tabControlPanel2;
        private DevComponents.DotNetBar.TabControlPanel tabControlPanel3;
        private DevComponents.DotNetBar.TabControlPanel tabControlPanel4;
        private DevComponents.DotNetBar.TabControlPanel tabControlPanel5;
        private DevComponents.DotNetBar.TabControlPanel tabControlPanel6;
        private DevComponents.DotNetBar.TabItem tabItem1;
        private DevComponents.DotNetBar.TabItem tabItem2;
        private DevComponents.DotNetBar.TabItem tabItem3;
        private DevComponents.DotNetBar.TabItem tabItem4;
        private DevComponents.DotNetBar.TabItem tabItem5;
        private DevComponents.DotNetBar.TabItem tabItem6;
        private ComboBox Years;

    }
}
