namespace SkypeApps
{
    using System;

    internal class SmileyArt
    {
        public static string Alright()
        {
            return (".(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(sun)(sun)(skype)" + Environment.NewLine + "(skype)(skype)(skype)(smile)(skype)(skype)(skype)(skype)(skype)(smile)(skype)(sun)(sun)(sun)(sun)" + Environment.NewLine + "(skype)(skype)(smile)(emo)(smile)(skype)(skype)(skype)(smile)(hug)(smile)(skype)(sun)(sun)(skype)" + Environment.NewLine + "(skype)(skype)(smile)(emo)(smile)(skype)(skype)(skype)(smile)(hug)(smile)(skype)(skype)(skype)(skype)" + Environment.NewLine + "(skype)(skype)(skype)(smile)(skype)(skype)(skype)(skype)(skype)(smile)(skype)(skype)(skype)(skype)(skype)" + Environment.NewLine + "(skype)(skype)(smile)(smile)(smile)(skype)(skype)(skype)(smile)(smile)(smile)(skype)(skype)(skype)(skype)" + Environment.NewLine + "(skype)(smile)(skype)(smile)(skype)(smile)(handshake)(smile)(skype)(smile)(skype)(smile)(skype)(skype)(skype)" + Environment.NewLine + "(skype)(smile)(skype)(smile)(skype)(skype)(skype)(skype)(skype)(smile)(skype)(smile)(skype)(skype)(skype)" + Environment.NewLine + "(skype)(skype)(skype)(smile)(skype)(skype)(skype)(skype)(skype)(smile)(skype)(skype)(skype)(skype)(skype)" + Environment.NewLine + "(skype)(skype)(smile)(skype)(smile)(skype)(skype)(skype)(smile)(skype)(smile)(skype)(skype)(skype)(skype)" + Environment.NewLine + "(skype)(skype)(smile)(skype)(smile)(skype)(skype)(skype)(smile)(skype)(smile)(skype)(skype)(skype)(skype)" + Environment.NewLine + "(skype)(skype)(smile)(skype)(smile)(skype)(skype)(skype)(smile)(skype)(smile)(skype)(skype)(skype)(skype)" + Environment.NewLine + "(skype)(flower)(smile)(flower)(smile)(flower)(skype)(flower)(smile)(flower)(smile)(flower)(skype)(flower)(skype)" + Environment.NewLine + "(flower)(flower)(flower)(flower)(flower)(flower)(flower)(flower)(flower)(flower)(flower)(flower)(flower)(flower)(flower)" + Environment.NewLine + "(flower)(flower)(flower)(flower)(flower)(flower)(flower)(flower)(flower)(flower)(flower)(flower)(flower)(flower)(flower)");
        }

        public static string Apple()
        {
            return (".(H)(H)(H)(H)(H)(H)(H)(H)(H)(H)(H)(H)(H)(H)(H)" + Environment.NewLine + "(H)(H)(H)(H)(H)(H)(H)(H)(H)(envy)(envy)(envy)(H)(H)(H)" + Environment.NewLine + "(H)(H)(H)(H)(H)(H)(H)(H)(envy)(envy)(envy)(H)(H)(H)(H)" + Environment.NewLine + "(H)(H)(H)(H)(H)(H)(H)(hug)(envy)(envy)(H)(H)(H)(H)(H)" + Environment.NewLine + "(H)(H)(H)(H)(H)(H)(H)(hug)(H)(H)(H)(H)(H)(H)(H)" + Environment.NewLine + "(H)(H)(H)(H)(envy)(envy)(envy)(hug)(envy)(envy)(envy)(H)(H)(H)(H)" + Environment.NewLine + "(H)(H)(H)(envy)(envy)(envy)(envy)(hug)(envy)(envy)(envy)(envy)(H)(H)(H)" + Environment.NewLine + "(H)(H)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(H)(H)" + Environment.NewLine + "(H)(H)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(H)(H)" + Environment.NewLine + "(H)(H)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(H)(H)" + Environment.NewLine + "(H)(H)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(H)(H)" + Environment.NewLine + "(H)(H)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(H)(H)" + Environment.NewLine + "(H)(H)(H)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(H)(H)(H)" + Environment.NewLine + "(H)(H)(H)(H)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(H)(H)(H)(H)" + Environment.NewLine + "(H)(H)(H)(H)(H)(envy)(envy)(envy)(envy)(envy)(H)(H)(H)(H)(H)");
        }

        public static string BearHug()
        {
            return (".(mail)(mail)(mail)(mail)(hug)(hug)(mail)(mail)(mail)(hug)(hug)(mail)(mail)(mail)(mail)" + Environment.NewLine + "(mail)(mail)(mail)(hug)(kiss)(kiss)(hug)(hug)(hug)(kiss)(kiss)(hug)(mail)(mail)(mail)" + Environment.NewLine + "(mail)(mail)(mail)(hug)(kiss)(kiss)(kiss)(kiss)(kiss)(kiss)(kiss)(hug)(mail)(mail)(mail)" + Environment.NewLine + "(mail)(mail)(mail)(mail)(hug)(kiss)(hug)(kiss)(hug)(kiss)(hug)(mail)(mail)(mail)(mail)" + Environment.NewLine + "(mail)(hug)(mail)(mail)(hug)(kiss)(kiss)(H)(kiss)(kiss)(hug)(mail)(mail)(hug)(mail)" + Environment.NewLine + "(hug)(kiss)(hug)(mail)(mail)(hug)(kiss)(kiss)(kiss)(hug)(mail)(mail)(hug)(kiss)(hug)" + Environment.NewLine + "(hug)(kiss)(kiss)(hug)(hug)(kiss)(hug)(hug)(hug)(kiss)(hug)(hug)(kiss)(kiss)(hug)" + Environment.NewLine + "(mail)(hug)(kiss)(kiss)(hug)(kiss)(kiss)(kiss)(kiss)(kiss)(hug)(kiss)(kiss)(hug)(mail)" + Environment.NewLine + "(mail)(mail)(hug)(kiss)(hug)(H)(H)(kiss)(kiss)(H)(H)(kiss)(hug)(mail)(mail)" + Environment.NewLine + "(mail)(mail)(mail)(hug)(H)(kiss)(H)(kiss)(H)(kiss)(H)(hug)(mail)(mail)(mail)" + Environment.NewLine + "(mail)(mail)(mail)(hug)(kiss)(H)(kiss)(kiss)(kiss)(H)(kiss)(hug)(mail)(mail)(mail)" + Environment.NewLine + "(mail)(mail)(mail)(hug)(H)(kiss)(kiss)(kiss)(H)(kiss)(kiss)(hug)(mail)(mail)(mail)" + Environment.NewLine + "(mail)(mail)(mail)(hug)(H)(H)(H)(kiss)(H)(H)(H)(hug)(mail)(mail)(mail)" + Environment.NewLine + "(mail)(mail)(hug)(kiss)(kiss)(hug)(hug)(kiss)(hug)(hug)(kiss)(kiss)(hug)(mail)(mail)" + Environment.NewLine + "(mail)(mail)(hug)(kiss)(kiss)(kiss)(kiss)(hug)(kiss)(kiss)(kiss)(kiss)(hug)(mail)(mail)");
        }

        public static string Boobs()
        {
            return (".(mail)(mail)(mail)(mail)(mail)(mail)(mail)(mail)(mail)(mail)(mail)(mail)(mail)(mail)(mail)" + Environment.NewLine + "(mail)(mail)(mail)(muscle)(muscle)(muscle)(muscle)(mail)(muscle)(muscle)(muscle)(muscle)(mail)(mail)(mail)" + Environment.NewLine + "(mail)(mail)(muscle)(muscle)(yes)(yes)(muscle)(muscle)(muscle)(yes)(yes)(muscle)(muscle)(mail)(mail)" + Environment.NewLine + "(mail)(muscle)(muscle)(yes)(yes)(yes)(yes)(muscle)(yes)(yes)(yes)(yes)(muscle)(muscle)(mail)" + Environment.NewLine + "(mail)(muscle)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(muscle)(mail)" + Environment.NewLine + "(muscle)(muscle)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(muscle)(muscle)" + Environment.NewLine + "(muscle)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(muscle)" + Environment.NewLine + "(muscle)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(muscle)" + Environment.NewLine + "(muscle)(yes)(yes)(yes)(yes)(yes)(yes)(muscle)(yes)(yes)(yes)(yes)(yes)(yes)(muscle)" + Environment.NewLine + "(muscle)(yes)(H)(yes)(yes)(yes)(yes)(muscle)(yes)(yes)(yes)(yes)(H)(yes)(muscle)" + Environment.NewLine + "(muscle)(yes)(yes)(yes)(yes)(yes)(muscle)(muscle)(muscle)(yes)(yes)(yes)(yes)(yes)(muscle)" + Environment.NewLine + "(muscle)(yes)(yes)(yes)(yes)(yes)(muscle)(muscle)(muscle)(yes)(yes)(yes)(yes)(yes)(muscle)" + Environment.NewLine + "(muscle)(muscle)(yes)(yes)(yes)(muscle)(muscle)(mail)(muscle)(muscle)(yes)(yes)(yes)(muscle)(muscle)" + Environment.NewLine + "(mail)(muscle)(muscle)(muscle)(muscle)(muscle)(mail)(mail)(mail)(muscle)(muscle)(muscle)(muscle)(muscle)(mail)" + Environment.NewLine + "(mail)(mail)(mail)(mail)(mail)(mail)(mail)(mail)(mail)(mail)(mail)(mail)(mail)(mail)(mail)");
        }

        public static string Boobs2()
        {
            return (".(smile)(smile)(smile)(smile)(smile)(emo)(handshake)(handshake)(handshake)(emo)(smile)(smile)(smile)(smile)(smile)" + Environment.NewLine + "(smile)(emo)(emo)(emo)(emo)(handshake)(handshake)(handshake)(handshake)(handshake)(emo)(emo)(emo)(emo)(smile)" + Environment.NewLine + "(emo)(handshake)(emo)(emo)(emo)(emo)(handshake)(handshake)(handshake)(emo)(emo)(emo)(emo)(handshake)(emo)" + Environment.NewLine + "(handshake)(emo)(yes)(yes)(yes)(yes)(emo)(handshake)(emo)(yes)(yes)(yes)(yes)(emo)(handshake)" + Environment.NewLine + "(emo)(yes)(yes)(yes)(yes)(yes)(yes)(emo)(yes)(yes)(yes)(yes)(yes)(yes)(emo)" + Environment.NewLine + "(emo)(yes)(yes)(devil)(devil)(yes)(yes)(emo)(yes)(yes)(devil)(devil)(yes)(yes)(emo)" + Environment.NewLine + "(emo)(yes)(yes)(devil)(devil)(yes)(yes)(emo)(yes)(yes)(devil)(devil)(yes)(yes)(emo)" + Environment.NewLine + "(emo)(yes)(yes)(yes)(yes)(yes)(yes)(emo)(yes)(yes)(yes)(yes)(yes)(yes)(emo)" + Environment.NewLine + "(smile)(emo)(yes)(yes)(yes)(yes)(emo)(handshake)(emo)(yes)(yes)(yes)(yes)(emo)(smile)" + Environment.NewLine + "(smile)(smile)(emo)(emo)(emo)(emo)(handshake)(handshake)(handshake)(emo)(emo)(emo)(emo)(smile)(smile)" + Environment.NewLine + "(smile)(smile)(smile)(emo)(handshake)(handshake)(handshake)(handshake)(handshake)(handshake)(handshake)(emo)(smile)(smile)(smile)" + Environment.NewLine + "(smile)(smile)(smile)(smile)(emo)(handshake)(handshake)(handshake)(handshake)(handshake)(emo)(smile)(smile)(smile)(smile)" + Environment.NewLine + "(smile)(smile)(smile)(smile)(emo)(handshake)(handshake)(sun)(handshake)(handshake)(emo)(smile)(smile)(smile)(smile)" + Environment.NewLine + "(smile)(smile)(smile)(smile)(emo)(handshake)(handshake)(handshake)(handshake)(handshake)(emo)(smile)(smile)(smile)(smile)" + Environment.NewLine + "(smile)(smile)(smile)(emo)(handshake)(handshake)(handshake)(handshake)(handshake)(handshake)(handshake)(emo)(smile)(smile)(smile)");
        }

        public static string Boobs3()
        {
            return (".(devil)(devil)(devil)(devil)(devil)(devil)(devil)(devil)(devil)(devil)(devil)(devil)(devil)(devil)(devil)" + Environment.NewLine + "(devil)(devil)(devil)(muscle)(muscle)(muscle)(muscle)(devil)(muscle)(muscle)(muscle)(muscle)(devil)(devil)(devil)" + Environment.NewLine + "(devil)(devil)(muscle)(muscle)(yes)(yes)(muscle)(muscle)(muscle)(yes)(yes)(muscle)(muscle)(devil)(devil)" + Environment.NewLine + "(devil)(muscle)(muscle)(yes)(yes)(yes)(yes)(muscle)(yes)(yes)(yes)(yes)(muscle)(muscle)(devil)" + Environment.NewLine + "(devil)(muscle)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(muscle)(devil)" + Environment.NewLine + "(muscle)(muscle)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(muscle)(muscle)" + Environment.NewLine + "(muscle)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(muscle)" + Environment.NewLine + "(muscle)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(yes)(muscle)" + Environment.NewLine + "(muscle)(yes)(yes)(yes)(yes)(yes)(yes)(muscle)(yes)(yes)(yes)(yes)(yes)(yes)(muscle)" + Environment.NewLine + "(muscle)(yes)(devil)(yes)(yes)(yes)(yes)(muscle)(yes)(yes)(yes)(yes)(devil)(yes)(muscle)" + Environment.NewLine + "(muscle)(yes)(yes)(yes)(yes)(yes)(muscle)(muscle)(muscle)(yes)(yes)(yes)(yes)(yes)(muscle)" + Environment.NewLine + "(muscle)(yes)(yes)(yes)(yes)(yes)(muscle)(muscle)(muscle)(yes)(yes)(yes)(yes)(yes)(muscle)" + Environment.NewLine + "(muscle)(muscle)(yes)(yes)(yes)(muscle)(muscle)(devil)(muscle)(muscle)(yes)(yes)(yes)(muscle)(muscle)" + Environment.NewLine + "(devil)(muscle)(muscle)(muscle)(muscle)(muscle)(devil)(devil)(devil)(muscle)(muscle)(muscle)(muscle)(muscle)(devil)" + Environment.NewLine + "(devil)(devil)(devil)(devil)(devil)(devil)(devil)(devil)(devil)(devil)(devil)(devil)(devil)(devil)(devil)");
        }

        public static string BUG()
        {
            return (".(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)" + Environment.NewLine + "(movie)(smile)(smile)(smile)(smile)(bug)(smile)(smile)(bug)(smile)(smile)(smile)(smile)(movie)" + Environment.NewLine + "(movie)(smile)(bug)(smile)(smile)(smile)(bug)(bug)(smile)(smile)(smile)(bug)(smile)(movie)" + Environment.NewLine + "(movie)(smile)(bug)(smile)(smile)(smile)(bug)(bug)(smile)(smile)(smile)(bug)(smile)(movie)" + Environment.NewLine + "(movie)(smile)(bug)(smile)(smile)(bug)(bug)(bug)(bug)(smile)(smile)(bug)(smile)(movie)" + Environment.NewLine + "(movie)(smile)(smile)(bug)(bug)(bug)(bug)(bug)(bug)(bug)(bug)(smile)(smile)(movie)" + Environment.NewLine + "(movie)(smile)(smile)(smile)(bug)(bug)(bug)(bug)(bug)(bug)(smile)(smile)(smile)(movie)" + Environment.NewLine + "(movie)(bug)(smile)(smile)(bug)(bug)(bug)(bug)(bug)(bug)(smile)(smile)(bug)(movie)" + Environment.NewLine + "(movie)(smile)(bug)(bug)(bug)(bug)(bug)(bug)(bug)(bug)(bug)(bug)(smile)(movie)" + Environment.NewLine + "(movie)(smile)(smile)(smile)(bug)(bug)(bug)(bug)(bug)(bug)(smile)(smile)(smile)(movie)" + Environment.NewLine + "(movie)(smile)(smile)(smile)(bug)(bug)(bug)(bug)(bug)(bug)(smile)(smile)(smile)(movie)" + Environment.NewLine + "(movie)(smile)(smile)(bug)(smile)(bug)(bug)(bug)(bug)(smile)(bug)(smile)(smile)(movie)" + Environment.NewLine + "(movie)(smile)(bug)(smile)(smile)(smile)(smile)(smile)(smile)(smile)(smile)(bug)(smile)(movie)" + Environment.NewLine + "(movie)(smile)(bug)(smile)(smile)(smile)(smile)(smile)(smile)(smile)(smile)(bug)(smile)(movie)" + Environment.NewLine + "(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)");
        }

        public static string Butterfly()
        {
            return (".(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)" + Environment.NewLine + "(skype)(H)(H)(skype)(star)(skype)(skype)(skype)(skype)(skype)(star)(skype)(H)(H)(skype)" + Environment.NewLine + "(skype)(H)(sun)(H)(skype)(star)(skype)(skype)(skype)(star)(skype)(H)(sun)(H)(skype)" + Environment.NewLine + "(skype)(H)(sun)(sun)(H)(skype)(star)(skype)(star)(skype)(H)(sun)(sun)(H)(skype)" + Environment.NewLine + "(skype)(H)(sun)(inlove)(sun)(H)(skype)(smile)(skype)(H)(sun)(inlove)(sun)(H)(skype)" + Environment.NewLine + "(skype)(skype)(H)(sun)(inlove)(sun)(H)(hug)(H)(sun)(inlove)(sun)(H)(skype)(skype)" + Environment.NewLine + "(skype)(skype)(H)(sun)(sun)(inlove)(sun)(hug)(sun)(inlove)(sun)(sun)(H)(skype)(skype)" + Environment.NewLine + "(skype)(skype)(skype)(H)(H)(H)(H)(hug)(H)(H)(H)(H)(skype)(skype)(skype)" + Environment.NewLine + "(skype)(H)(H)(sun)(sun)(inlove)(sun)(hug)(sun)(inlove)(sun)(sun)(H)(H)(skype)" + Environment.NewLine + "(skype)(H)(sun)(inlove)(inlove)(sun)(H)(hug)(H)(sun)(inlove)(inlove)(sun)(H)(skype)" + Environment.NewLine + "(skype)(H)(sun)(sun)(sun)(H)(skype)(hug)(skype)(H)(sun)(sun)(sun)(H)(skype)" + Environment.NewLine + "(skype)(skype)(H)(H)(H)(skype)(skype)(skype)(skype)(skype)(H)(H)(H)(skype)(skype)" + Environment.NewLine + "(skype)(H)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(H)(skype)" + Environment.NewLine + "(H)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(H)" + Environment.NewLine + "(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)");
        }

        public static string Dick()
        {
            return (".(smile)(smile)(smile)(smile)(smile)(smile)(smile)(smile)(smile)(smile)(smile)(smile)(smile)(smile)" + Environment.NewLine + "(smile)(smile)(smile)(smile)(smile)(smile)(muscle)(muscle)(smile)(smile)(smile)(smile)(smile)(smile)" + Environment.NewLine + "(smile)(smile)(smile)(smile)(smile)(muscle)(muscle)(muscle)(muscle)(smile)(smile)(smile)(smile)(smile)" + Environment.NewLine + "(smile)(smile)(smile)(smile)(muscle)(muscle)(muscle)(muscle)(muscle)(muscle)(smile)(smile)(smile)(smile)" + Environment.NewLine + "(smile)(smile)(smile)(smile)(smile)(muscle)(muscle)(muscle)(muscle)(smile)(smile)(smile)(smile)(smile)" + Environment.NewLine + "(smile)(smile)(smile)(smile)(smile)(muscle)(muscle)(muscle)(muscle)(smile)(smile)(smile)(smile)(smile)" + Environment.NewLine + "(smile)(smile)(smile)(smile)(smile)(muscle)(muscle)(muscle)(muscle)(smile)(smile)(smile)(smile)(smile)" + Environment.NewLine + "(smile)(smile)(smile)(smile)(smile)(muscle)(muscle)(muscle)(muscle)(smile)(smile)(smile)(smile)(smile)" + Environment.NewLine + "(smile)(smile)(smile)(smile)(smile)(muscle)(muscle)(muscle)(muscle)(smile)(smile)(smile)(smile)(smile)" + Environment.NewLine + "(smile)(smile)(smile)(smile)(smile)(muscle)(muscle)(muscle)(muscle)(smile)(smile)(smile)(smile)(smile)" + Environment.NewLine + "(smile)(smile)(muscle)(muscle)(muscle)(muscle)(muscle)(muscle)(muscle)(muscle)(muscle)(muscle)(smile)(smile)" + Environment.NewLine + "(smile)(muscle)(muscle)(muscle)(muscle)(muscle)(muscle)(muscle)(muscle)(muscle)(muscle)(muscle)(muscle)(smile)" + Environment.NewLine + "(smile)(muscle)(muscle)(muscle)(muscle)(muscle)(muscle)(muscle)(muscle)(muscle)(muscle)(muscle)(muscle)(smile)" + Environment.NewLine + "(smile)(muscle)(muscle)(muscle)(muscle)(muscle)(muscle)(muscle)(muscle)(muscle)(muscle)(muscle)(muscle)(smile)" + Environment.NewLine + "(smile)(smile)(smile)(muscle)(muscle)(muscle)(smile)(smile)(muscle)(muscle)(muscle)(muscle)(smile)(smile)");
        }

        public static string Drink()
        {
            return (".(d)(d)(d)(d)(d)(d)(d)" + Environment.NewLine + "(d)(d)(d)(d)(d)(d)(d)" + Environment.NewLine + "(music)(d)(d)(d)(d)(d)(music)" + Environment.NewLine + "(music)(music)(d)(d)(d)(music)(music)" + Environment.NewLine + "(music)(music)(music)(d)(music)(music)(music)" + Environment.NewLine + "(music)(music)(music)(d)(music)(music)(music)" + Environment.NewLine + "(music)(music)(music)(d)(music)(music)(music)" + Environment.NewLine + "(music)(music)(music)(d)(music)(music)(music)(d)(d)(d)(d)(d)(d)(d)");
        }

        public static string Fuck()
        {
            return (".(bug)(punch)(punch)(punch)(punch)(bug)(bug)(bug)(bug)(bug)(bug)(rock)(rock)(rock)(rock)" + Environment.NewLine + "(bug)(punch)(bug)(bug)(bug)(bug)(bug)(bug)(bug)(bug)(bug)(bug)(rock)(rock)(rock)" + Environment.NewLine + "(bug)(punch)(punch)(punch)(punch)(bug)(bug)(bug)(bug)(bug)(bug)(bug)(bug)(rock)(rock)" + Environment.NewLine + "(bug)(punch)(bug)(bug)(bug)(bug)(bug)(bug)(bug)(bug)(bug)(bug)(bug)(bug)(rock)" + Environment.NewLine + "(bug)(punch)(bug)(punch)(bug)(bug)(bug)(punch)(bug)(bug)(bug)(bug)(bug)(bug)(bug)" + Environment.NewLine + "(bug)(bug)(bug)(punch)(bug)(bug)(bug)(punch)(bug)(bug)(bug)(bug)(bug)(bug)(bug)" + Environment.NewLine + "(bug)(bug)(bug)(punch)(bug)(bug)(bug)(punch)(bug)(bug)(bug)(bug)(bug)(bug)(bug)" + Environment.NewLine + "(bug)(bug)(bug)(punch)(bug)(bug)(bug)(punch)(bug)(bug)(bug)(bug)(bug)(bug)(bug)" + Environment.NewLine + "(bug)(bug)(bug)(bug)(punch)(punch)(punch)(bug)(bug)(bug)(bug)(bug)(bug)(bug)(bug)" + Environment.NewLine + "(bug)(bug)(bug)(bug)(bug)(bug)(bug)(punch)(punch)(bug)(bug)(punch)(bug)(bug)(punch)" + Environment.NewLine + "(bug)(bug)(bug)(bug)(bug)(bug)(punch)(bug)(bug)(bug)(bug)(punch)(bug)(punch)(bug)" + Environment.NewLine + "(rock)(bug)(bug)(bug)(bug)(punch)(bug)(bug)(bug)(bug)(bug)(punch)(punch)(bug)(bug)" + Environment.NewLine + "(rock)(rock)(bug)(bug)(bug)(punch)(bug)(bug)(bug)(bug)(bug)(punch)(punch)(bug)(bug)" + Environment.NewLine + "(rock)(rock)(rock)(bug)(bug)(bug)(punch)(bug)(bug)(bug)(bug)(punch)(bug)(punch)(bug)" + Environment.NewLine + "(rock)(rock)(rock)(rock)(bug)(bug)(bug)(punch)(punch)(bug)(bug)(punch)(bug)(bug)(punch)");
        }

        public static string ILoveSex()
        {
            return (".(H)(H)(H)(H)(skype)(skype)(H)(H)(skype)(skype)(skype)(H)(H)(skype)(skype)" + Environment.NewLine + "(skype)(H)(H)(skype)(skype)(H)(H)(H)(H)(skype)(H)(H)(H)(H)(skype)" + Environment.NewLine + "(skype)(H)(H)(skype)(skype)(H)(H)(H)(H)(H)(H)(H)(H)(H)(skype)" + Environment.NewLine + "(skype)(H)(H)(skype)(skype)(skype)(H)(H)(H)(H)(H)(H)(H)(skype)(skype)" + Environment.NewLine + "(skype)(H)(H)(skype)(skype)(skype)(skype)(H)(H)(H)(H)(H)(skype)(skype)(skype)" + Environment.NewLine + "(skype)(H)(H)(skype)(skype)(skype)(skype)(skype)(H)(H)(H)(skype)(skype)(skype)(skype)" + Environment.NewLine + "(H)(H)(H)(H)(skype)(skype)(skype)(skype)(skype)(H)(skype)(skype)(skype)(skype)(skype)" + Environment.NewLine + "(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)" + Environment.NewLine + "(skype)(H)(H)(H)(skype)(H)(H)(H)(H)(skype)(H)(skype)(skype)(skype)(H)" + Environment.NewLine + "(H)(skype)(skype)(skype)(skype)(H)(skype)(skype)(H)(skype)(H)(skype)(skype)(skype)(H)" + Environment.NewLine + "(H)(skype)(skype)(skype)(skype)(H)(skype)(skype)(skype)(skype)(skype)(H)(skype)(H)(skype)" + Environment.NewLine + "(skype)(H)(H)(H)(skype)(H)(H)(H)(skype)(skype)(skype)(skype)(H)(skype)(skype)" + Environment.NewLine + "(skype)(skype)(skype)(H)(skype)(H)(skype)(skype)(skype)(skype)(skype)(H)(skype)(H)(skype)" + Environment.NewLine + "(H)(skype)(skype)(H)(skype)(H)(skype)(skype)(H)(skype)(H)(skype)(skype)(skype)(H)" + Environment.NewLine + "(skype)(H)(H)(skype)(skype)(H)(H)(H)(H)(skype)(H)(skype)(skype)(skype)(H)");
        }

        public static string JerkOff()
        {
            return (".(movie)(movie)(sun)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)" + Environment.NewLine + "(movie)(sun)(sun)(sun)(movie)(movie)(movie)(movie)(sun)(movie)(movie)(movie)(movie)(movie)(movie)" + Environment.NewLine + "(movie)(sun)(sun)(sun)(sun)(sun)(sun)(sun)(sun)(sun)(movie)(movie)(movie)(movie)(movie)" + Environment.NewLine + "(movie)(movie)(sun)(sun)(sun)(sun)(sun)(sun)(sun)(angry)(angry)(movie)(movie)(movie)(movie)" + Environment.NewLine + "(movie)(sun)(sun)(sun)(sun)(sun)(sun)(sun)(sun)(sun)(movie)(rain)(rain)(movie)(movie)" + Environment.NewLine + "(movie)(sun)(sun)(sun)(movie)(movie)(movie)(movie)(sun)(movie)(movie)(movie)(rain)(movie)(movie)" + Environment.NewLine + "(movie)(movie)(sun)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)" + Environment.NewLine + "(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(rain)(movie)(movie)(movie)" + Environment.NewLine + "(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(rain)(movie)(movie)(movie)" + Environment.NewLine + "(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(rain)(movie)(movie)(movie)(movie)" + Environment.NewLine + "(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(rain)(movie)(movie)(movie)(movie)" + Environment.NewLine + "(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(rain)(movie)(movie)(movie)" + Environment.NewLine + "(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)" + Environment.NewLine + "(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(envy)(envy)(envy)(envy)(movie)(movie)" + Environment.NewLine + "(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)(movie)");
        }

        public static string KissYou()
        {
            return (".(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)" + Environment.NewLine + "(skype)(kiss)(skype)(kiss)(skype)(kiss)(skype)(skype)(kiss)(kiss)(skype)(skype)(kiss)(kiss)(skype)" + Environment.NewLine + "(skype)(kiss)(skype)(kiss)(skype)(kiss)(skype)(kiss)(skype)(skype)(skype)(kiss)(skype)(skype)(skype)" + Environment.NewLine + "(skype)(kiss)(kiss)(skype)(skype)(kiss)(skype)(skype)(kiss)(skype)(skype)(skype)(kiss)(skype)(skype)" + Environment.NewLine + "(skype)(kiss)(skype)(kiss)(skype)(kiss)(skype)(skype)(skype)(kiss)(skype)(skype)(skype)(kiss)(skype)" + Environment.NewLine + "(skype)(kiss)(skype)(kiss)(skype)(kiss)(skype)(kiss)(kiss)(skype)(skype)(kiss)(kiss)(skype)(skype)" + Environment.NewLine + "(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)" + Environment.NewLine + "(skype)(skype)(kiss)(skype)(kiss)(skype)(skype)(kiss)(skype)(skype)(kiss)(skype)(kiss)(skype)(skype)" + Environment.NewLine + "(skype)(skype)(kiss)(skype)(kiss)(skype)(kiss)(skype)(kiss)(skype)(kiss)(skype)(kiss)(skype)(skype)" + Environment.NewLine + "(skype)(skype)(skype)(kiss)(kiss)(skype)(kiss)(skype)(kiss)(skype)(kiss)(skype)(kiss)(skype)(skype)" + Environment.NewLine + "(skype)(skype)(skype)(skype)(kiss)(skype)(kiss)(skype)(kiss)(skype)(kiss)(skype)(kiss)(skype)(skype)" + Environment.NewLine + "(skype)(skype)(kiss)(kiss)(skype)(skype)(skype)(kiss)(skype)(skype)(skype)(kiss)(skype)(skype)(skype)" + Environment.NewLine + "(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)");
        }

        public static string LOL()
        {
            return (".(sun)(sun)(sun)(sun)(sun)(sun)(sun)(sun)(sun)(sun)(sun)(sun)(sun)" + Environment.NewLine + "(sun)(rain)(sun)(sun)(sun)(rain)(rain)(rain)(sun)(rain)(sun)(sun)(sun)" + Environment.NewLine + "(sun)(rain)(sun)(sun)(sun)(rain)(sun)(rain)(sun)(rain)(sun)(sun)(sun)" + Environment.NewLine + "(sun)(rain)(sun)(sun)(sun)(rain)(sun)(rain)(sun)(rain)(sun)(sun)(sun)" + Environment.NewLine + "(sun)(rain)(rain)(rain)(sun)(rain)(rain)(rain)(sun)(rain)(rain)(rain)(sun)" + Environment.NewLine + "(sun)(sun)(sun)(sun)(sun)(sun)(sun)(sun)(sun)(sun)(sun)(sun)(sun)");
        }

        public static string LOVE()
        {
            return (".(flower)(flower)(flower)(H)(H)(H)(flower)(flower)(flower)(H)(H)(H)(flower)(flower)(flower)" + Environment.NewLine + "(flower)(flower)(H)(skype)(skype)(skype)(H)(flower)(H)(skype)(skype)(skype)(H)(flower)(flower)" + Environment.NewLine + "(flower)(H)(skype)(skype)(skype)(skype)(skype)(H)(skype)(skype)(skype)(skype)(skype)(H)(flower)" + Environment.NewLine + "(H)(skype)(skype)(skype)(H)(H)(skype)(skype)(skype)(H)(H)(skype)(skype)(skype)(H)" + Environment.NewLine + "(H)(skype)(skype)(H)(H)(H)(H)(skype)(H)(H)(H)(H)(skype)(skype)(H)" + Environment.NewLine + "(H)(skype)(skype)(H)(H)(H)(H)(H)(H)(H)(H)(H)(skype)(skype)(H)" + Environment.NewLine + "(H)(skype)(skype)(H)(H)(H)(H)(H)(H)(H)(H)(H)(skype)(skype)(H)" + Environment.NewLine + "(flower)(H)(skype)(skype)(H)(H)(H)(H)(H)(H)(H)(skype)(skype)(H)(flower)" + Environment.NewLine + "(flower)(flower)(H)(skype)(skype)(H)(H)(H)(H)(H)(skype)(skype)(H)(flower)(flower)" + Environment.NewLine + "(flower)(flower)(flower)(H)(skype)(skype)(H)(H)(H)(skype)(skype)(H)(flower)(flower)(flower)" + Environment.NewLine + "(flower)(flower)(flower)(flower)(H)(skype)(skype)(H)(skype)(skype)(H)(flower)(flower)(flower)(flower)" + Environment.NewLine + "(flower)(flower)(flower)(flower)(flower)(H)(skype)(skype)(skype)(H)(flower)(flower)(flower)(flower)(flower)" + Environment.NewLine + "(flower)(flower)(flower)(flower)(flower)(flower)(H)(skype)(H)(flower)(flower)(flower)(flower)(flower)(flower)" + Environment.NewLine + "(flower)(flower)(flower)(flower)(flower)(flower)(flower)(H)(flower)(flower)(flower)(flower)(flower)(flower)(flower)" + Environment.NewLine + "(flower)(flower)(flower)(flower)(flower)(flower)(flower)(H)(flower)(flower)(flower)(flower)(flower)(flower)(flower)");
        }

        public static string OKLOVE()
        {
            return (".(nod)(nod)(nod)(nod)(nod)(nod)(nod)(nod)(nod)(nod)" + Environment.NewLine + "(nod)(h)(h)(h)(nod)(h)(nod)(nod)(h)(nod)" + Environment.NewLine + "(nod)(h)(nod)(h)(nod)(h)(nod)(h)(nod)(nod)" + Environment.NewLine + "(nod)(h)(nod)(h)(nod)(h)(h)(nod)(nod)(nod)" + Environment.NewLine + "(nod)(h)(nod)(h)(nod)(h)(h)(nod)(nod)(nod)" + Environment.NewLine + "(nod)(h)(nod)(h)(nod)(h)(nod)(h)(nod)(nod)" + Environment.NewLine + "(nod)(h)(h)(h)(nod)(h)(nod)(nod)(h)(nod)" + Environment.NewLine + "(nod)(nod)(nod)(nod)(nod)(nod)(nod)(nod)(nod)(nod)");
        }

        public static string Rabbit()
        {
            return (".(smile)(smile)(smile)(smile)(sun)(sun)(sun)(sun)(sun)(sun)(smile)(smile)(smile)(smile)(smile)" + Environment.NewLine + "(smile)(smile)(smile)(sun)(skype)(skype)(sun)(sun)(skype)(sun)(smile)(smile)(smile)(smile)(smile)" + Environment.NewLine + "(smile)(smile)(smile)(sun)(skype)(sun)(sun)(skype)(skype)(sun)(smile)(smile)(smile)(smile)(smile)" + Environment.NewLine + "(smile)(smile)(sun)(skype)(sun)(sun)(skype)(skype)(skype)(sun)(smile)(smile)(smile)(smile)(smile)" + Environment.NewLine + "(smile)(smile)(sun)(skype)(sun)(skype)(skype)(skype)(sun)(smile)(smile)(smile)(smile)(smile)(smile)" + Environment.NewLine + "(smile)(smile)(sun)(sun)(skype)(skype)(skype)(sun)(sun)(sun)(sun)(smile)(smile)(smile)(smile)" + Environment.NewLine + "(smile)(sun)(skype)(skype)(skype)(skype)(sun)(skype)(skype)(skype)(skype)(sun)(smile)(smile)(smile)" + Environment.NewLine + "(sun)(skype)(skype)(H)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(sun)(smile)(smile)" + Environment.NewLine + "(sun)(hug)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(sun)(skype)(skype)(skype)(sun)(sun)" + Environment.NewLine + "(sun)(skype)(skype)(skype)(skype)(skype)(skype)(skype)(sun)(skype)(skype)(skype)(skype)(sun)(skype)" + Environment.NewLine + "(smile)(sun)(sun)(sun)(skype)(skype)(skype)(skype)(sun)(skype)(skype)(skype)(skype)(skype)(skype)" + Environment.NewLine + "(smile)(smile)(flower)(sun)(skype)(skype)(skype)(skype)(skype)(sun)(skype)(skype)(skype)(skype)(envy)" + Environment.NewLine + "(flower)(envy)(envy)(envy)(envy)(skype)(skype)(skype)(sun)(skype)(skype)(skype)(skype)(envy)(envy)" + Environment.NewLine + "(envy)(flower)(envy)(envy)(skype)(skype)(skype)(sun)(skype)(skype)(skype)(skype)(envy)(envy)(envy)" + Environment.NewLine + "(envy)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(envy)(envy)");
        }

        public static string SuperMario()
        {
            return (".(mail)(mail)(mail)(mail)(devil)(devil)(devil)(devil)(mail)(mail)(mail)(mail)(mail)" + Environment.NewLine + "(mail)(mail)(mail)(devil)(devil)(devil)(devil)(devil)(devil)(devil)(devil)(mail)(mail)" + Environment.NewLine + "(mail)(mail)(mail)(hug)(hug)(hug)(sun)(movie)(sun)(mail)(mail)(mail)(mail)" + Environment.NewLine + "(mail)(mail)(hug)(sun)(hug)(sun)(sun)(sun)(sun)(sun)(sun)(mail)(mail)" + Environment.NewLine + "(mail)(mail)(hug)(sun)(hug)(hug)(sun)(sun)(hug)(sun)(sun)(sun)(mail)" + Environment.NewLine + "(mail)(mail)(hug)(hug)(sun)(sun)(sun)(hug)(hug)(hug)(hug)(mail)(mail)" + Environment.NewLine + "(mail)(mail)(mail)(mail)(sun)(sun)(sun)(sun)(sun)(sun)(mail)(mail)(mail)" + Environment.NewLine + "(mail)(mail)(mail)(hug)(devil)(hug)(hug)(hug)(hug)(mail)(mail)(mail)(mail)" + Environment.NewLine + "(mail)(mail)(hug)(hug)(devil)(hug)(hug)(hug)(devil)(hug)(hug)(mail)(mail)" + Environment.NewLine + "(mail)(hug)(hug)(hug)(devil)(devil)(devil)(devil)(devil)(hug)(hug)(sun)(mail)" + Environment.NewLine + "(mail)(sun)(sun)(sun)(devil)(devil)(devil)(devil)(devil)(hug)(sun)(sun)(mail)" + Environment.NewLine + "(mail)(mail)(mail)(devil)(devil)(devil)(devil)(devil)(devil)(devil)(mail)(mail)(mail)" + Environment.NewLine + "(mail)(mail)(mail)(devil)(devil)(devil)(mail)(devil)(devil)(devil)(mail)(mail)(mail)" + Environment.NewLine + "(mail)(mail)(hug)(hug)(hug)(hug)(mail)(hug)(hug)(hug)(hug)(mail)(mail)" + Environment.NewLine + "(mail)(hug)(hug)(hug)(hug)(hug)(mail)(hug)(hug)(hug)(hug)(hug)(mail)");
        }

        public static string TeddyBear()
        {
            return (".(smile)(smile)(smile)(smile)(hug)(hug)(smile)(smile)(smile)(hug)(hug)(smile)(smile)(smile)(smile)" + Environment.NewLine + "(smile)(smile)(smile)(hug)(hug)(hug)(hug)(hug)(hug)(hug)(hug)(hug)(smile)(smile)(smile)" + Environment.NewLine + "(smile)(smile)(smile)(hug)(hug)(hug)(hug)(hug)(hug)(hug)(hug)(hug)(smile)(smile)(smile)" + Environment.NewLine + "(smile)(smile)(smile)(smile)(hug)(hug)(hug)(H)(hug)(hug)(hug)(smile)(smile)(smile)(smile)" + Environment.NewLine + "(smile)(hug)(smile)(smile)(hug)(hug)(hug)(hug)(hug)(hug)(hug)(smile)(smile)(hug)(smile)" + Environment.NewLine + "(hug)(hug)(hug)(smile)(smile)(hug)(hug)(hug)(hug)(hug)(smile)(smile)(hug)(hug)(hug)" + Environment.NewLine + "(hug)(hug)(hug)(hug)(hug)(hug)(hug)(hug)(hug)(hug)(hug)(hug)(hug)(hug)(hug)" + Environment.NewLine + "(smile)(hug)(hug)(hug)(hug)(hug)(hug)(hug)(hug)(hug)(hug)(hug)(hug)(hug)(smile)" + Environment.NewLine + "(smile)(smile)(hug)(hug)(hug)(H)(H)(hug)(H)(H)(hug)(hug)(hug)(smile)(smile)" + Environment.NewLine + "(smile)(smile)(smile)(hug)(H)(H)(H)(H)(H)(H)(H)(hug)(smile)(smile)(smile)" + Environment.NewLine + "(smile)(smile)(smile)(hug)(H)(H)(H)(H)(H)(H)(H)(hug)(smile)(smile)(smile)" + Environment.NewLine + "(smile)(smile)(smile)(hug)(H)(H)(H)(H)(H)(H)(H)(hug)(smile)(smile)(smile)" + Environment.NewLine + "(smile)(smile)(smile)(hug)(hug)(H)(H)(H)(H)(H)(hug)(hug)(smile)(smile)(smile)" + Environment.NewLine + "(smile)(smile)(hug)(hug)(hug)(hug)(H)(H)(H)(hug)(hug)(hug)(hug)(smile)(smile)" + Environment.NewLine + "(smile)(smile)(hug)(hug)(hug)(hug)(hug)(H)(hug)(hug)(hug)(hug)(hug)(smile)(smile)");
        }
    }
}

